import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    sites: "Sites",
    analytics: "Analytics",
    reports: "Reports",
    templates: "Templates",
    users: "Users",
    billing: "Billing",
    settings: "Settings",
    login: "Log in",
    
    // Common
    search: "Search",
    filter: "Filter",
    export: "Export",
    delete: "Delete",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    noResults: "No results found",
    actions: "Actions",
    status: "Status",
    date: "Date",
    view: "View",
    addNew: "Add New",
    
    // Sites Page
    sitesTitle: "Sites",
    sitesSubtitle: "Manage and monitor your websites",
    addSite: "Add Site",
    addSiteTitle: "Add New Site",
    addSiteDescription: "Enter the domain of the website you want to monitor",
    domainPlaceholder: "example.com",
    adding: "Adding...",
    noSitesYet: "No sites yet",
    noSitesDescription: "Add your first website to start monitoring",
    crawlNow: "Crawl Now",
    crawling: "Crawling...",
    schedule: "Schedule",
    domain: "Domain",
    lastCrawl: "Last Crawl",
    openIssues: "Open Issues",
    critical: "critical",
    total: "total",
    visitSite: "Visit site",
    enabled: "Enabled",
    notScheduled: "Not scheduled",
    never: "Never",
    
    // Landing - Hero
    heroPreline: "AI-powered SEO analysis for modern websites",
    heroTitle1: "Keep your website",
    heroTitle2: "SEO-optimized",
    heroSubtitle: "Automatic scanning, AI prioritization, and comprehensive reports. Everything you need to maintain and improve your website's SEO health.",
    heroCtaPrimary: "Start Free Trial",
    heroCtaSecondary: "View Demo",
    
    // Landing - Features
    featuresTitle: "Everything you need for SEO monitoring",
    featuresSubtitle: "From automatic scanning to detailed reports - we have all the tools you need",
    
    feature1Title: "Automatic Site Crawling",
    feature1Desc: "Crawls all pages on your website and automatically identifies SEO issues",
    
    feature2Title: "Prioritized Issues",
    feature2Desc: "AI-driven analysis that ranks issues by importance and impact",
    
    feature3Title: "Performance Metrics",
    feature3Desc: "Monitor Core Web Vitals, page speed, and other important performance metrics",
    
    feature4Title: "Automated Reports",
    feature4Desc: "Schedule weekly or monthly PDF reports for clients",
    
    feature5Title: "Scheduled Crawls",
    feature5Desc: "Automatic monitoring of website changes and new issues",
    
    feature6Title: "Team Management",
    feature6Desc: "Manage access for your team with roles and permissions",
    
    // Landing - Use Cases
    useCasesTitle: "Perfect for everyone working with SEO",
    useCasesSubtitle: "Whether you manage your own website or deliver services to clients",
    
    useCase1Title: "For Businesses",
    useCase1Desc: "Perfect for companies that want full control over their SEO health",
    useCase1Benefit1: "Identify and fix SEO issues before they affect rankings",
    useCase1Benefit2: "Monitor competitive metrics like backlinks and domain rating",
    useCase1Benefit3: "Get AI-driven recommendations for improvements",
    useCase1Benefit4: "Export data for deeper analysis",
    useCase1Cta: "Start Free Trial",
    
    useCase2Title: "For Agencies & Consultants",
    useCase2Desc: "Perfect for those delivering SEO services to multiple clients",
    useCase2Benefit1: "White-label reports with your own branding",
    useCase2Benefit2: "Manage multiple client websites from one account",
    useCase2Benefit3: "Automate repetitive SEO tasks",
    useCase2Benefit4: "Show the value of your services with detailed reports",
    useCase2Cta: "Explore Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Choose the plan that fits you",
    pricingSubtitle: "All plans include a 14-day free trial. No credit card required.",
    pricingPopular: "Popular",
    pricingPerMonth: "/month",
    pricingSites: "websites",
    pricingCrawls: "crawls/month",
    pricingUnlimited: "Unlimited",
    pricingCtaFree: "Get started",
    pricingCtaPaid: "Choose plan",
    
    // Landing - Final CTA
    ctaTitle: "Ready to optimize your website?",
    ctaSubtitle: "Join thousands of businesses and agencies using Fixlist to keep their websites SEO-optimized.",
    ctaButton: "Start Free Trial Today",
    ctaNotice: "No credit card required • 14-day free trial • Cancel anytime",
    
    // Landing - Footer
    footerCopyright: "All rights reserved.",
  },
  no: {
    // Navigation
    sites: "Nettsteder",
    analytics: "Analyse",
    reports: "Rapporter",
    templates: "Maler",
    users: "Brukere",
    billing: "Fakturering",
    settings: "Innstillinger",
    login: "Logg inn",
    
    // Common
    search: "Søk",
    filter: "Filtrer",
    export: "Eksporter",
    delete: "Slett",
    edit: "Rediger",
    save: "Lagre",
    cancel: "Avbryt",
    loading: "Laster...",
    noResults: "Ingen resultater funnet",
    actions: "Handlinger",
    status: "Status",
    date: "Dato",
    view: "Vis",
    addNew: "Legg til ny",
    
    // Sites Page
    sitesTitle: "Nettsteder",
    sitesSubtitle: "Administrer og overvåk nettstedene dine",
    addSite: "Legg til nettsted",
    addSiteTitle: "Legg til nytt nettsted",
    addSiteDescription: "Skriv inn domenet til nettstedet du vil overvåke",
    domainPlaceholder: "eksempel.no",
    adding: "Legger til...",
    noSitesYet: "Ingen nettsteder ennå",
    noSitesDescription: "Legg til ditt første nettsted for å starte overvåking",
    crawlNow: "Crawl nå",
    crawling: "Crawler...",
    schedule: "Planlegg",
    domain: "Domene",
    lastCrawl: "Siste crawl",
    openIssues: "Åpne problemer",
    critical: "kritiske",
    total: "totalt",
    visitSite: "Besøk nettsted",
    enabled: "Aktivert",
    notScheduled: "Ikke planlagt",
    never: "Aldri",
    
    // Landing - Hero
    heroPreline: "AI-drevet SEO-analyse for moderne nettsteder",
    heroTitle1: "Hold nettstedet ditt",
    heroTitle2: "SEO-optimalisert",
    heroSubtitle: "Automatisk skanning, AI-prioritering og omfattende rapporter. Alt du trenger for å opprettholde og forbedre SEO-helsen til nettsidene dine.",
    heroCtaPrimary: "Start Gratis Prøveperiode",
    heroCtaSecondary: "Se Demo",
    
    // Landing - Features
    featuresTitle: "Alt du trenger for SEO-overvåking",
    featuresSubtitle: "Fra automatisk skanning til detaljerte rapporter - vi har alle verktøyene du trenger",
    
    feature1Title: "Automatisk Nettstedskanning",
    feature1Desc: "Crawler alle sidene på nettstedet ditt og identifiserer SEO-problemer automatisk",
    
    feature2Title: "Prioriterte Problemer",
    feature2Desc: "AI-drevet analyse som rangerer problemer etter viktighet og påvirkning",
    
    feature3Title: "Performance Metrics",
    feature3Desc: "Overvåk Core Web Vitals, sidetid, og andre viktige ytelsesmetrikker",
    
    feature4Title: "Automatiske Rapporter",
    feature4Desc: "Planlegg ukentlige eller månedlige PDF-rapporter til kunder",
    
    feature5Title: "Planlagte Crawls",
    feature5Desc: "Automatisk overvåking av nettsted-endringer og nye problemer",
    
    feature6Title: "Team Management",
    feature6Desc: "Administrer tilganger for teamet ditt med roller og tillatelser",
    
    // Landing - Use Cases
    useCasesTitle: "Perfekt for alle som arbeider med SEO",
    useCasesSubtitle: "Uansett om du administrerer ditt eget nettsted eller leverer tjenester til kunder",
    
    useCase1Title: "For Bedrifter",
    useCase1Desc: "Perfekt for bedrifter som vil ha full kontroll over sin SEO-helse",
    useCase1Benefit1: "Identifiser og fiks SEO-problemer før de påvirker rangeringer",
    useCase1Benefit2: "Overvåk konkurransedyktige metrics som backlinks og domain rating",
    useCase1Benefit3: "Få AI-drevne anbefalinger for forbedringer",
    useCase1Benefit4: "Eksporter data for dypere analyse",
    useCase1Cta: "Start Gratis Prøveperiode",
    
    useCase2Title: "For Byråer & Konsulenter",
    useCase2Desc: "Perfekt for de som leverer SEO-tjenester til flere kunder",
    useCase2Benefit1: "White-label rapporter med din egen branding",
    useCase2Benefit2: "Håndter flere kunders nettsteder fra én konto",
    useCase2Benefit3: "Automatiser repeterende SEO-oppgaver",
    useCase2Benefit4: "Vis verdien av dine tjenester med detaljerte rapporter",
    useCase2Cta: "Utforsk Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Velg planen som passer deg",
    pricingSubtitle: "Alle planer inkluderer 14 dagers gratis prøveperiode. Ingen kredittkort nødvendig.",
    pricingPopular: "Populær",
    pricingPerMonth: "/måned",
    pricingSites: "nettsteder",
    pricingCrawls: "crawls/måned",
    pricingUnlimited: "Ubegrensede",
    pricingCtaFree: "Kom i gang",
    pricingCtaPaid: "Velg plan",
    
    // Landing - Final CTA
    ctaTitle: "Klar til å optimalisere nettstedet ditt?",
    ctaSubtitle: "Bli med tusenvis av bedrifter og byråer som bruker Fixlist for å holde nettstedene sine SEO-optimaliserte.",
    ctaButton: "Start Gratis Prøveperiode i dag",
    ctaNotice: "Ingen kredittkort nødvendig • 14 dagers gratis prøveperiode • Avbryt når som helst",
    
    // Landing - Footer
    footerCopyright: "Alle rettigheter forbeholdt.",
  },
  sv: {
    // Navigation
    sites: "Webbplatser",
    analytics: "Analys",
    reports: "Rapporter",
    templates: "Mallar",
    users: "Användare",
    billing: "Fakturering",
    settings: "Inställningar",
    login: "Logga in",
    
    // Common
    search: "Sök",
    filter: "Filtrera",
    export: "Exportera",
    delete: "Radera",
    edit: "Redigera",
    save: "Spara",
    cancel: "Avbryt",
    loading: "Laddar...",
    noResults: "Inga resultat hittades",
    actions: "Åtgärder",
    status: "Status",
    date: "Datum",
    view: "Visa",
    addNew: "Lägg till ny",
    
    // Sites Page
    sitesTitle: "Webbplatser",
    sitesSubtitle: "Hantera och övervaka dina webbplatser",
    addSite: "Lägg till webbplats",
    addSiteTitle: "Lägg till ny webbplats",
    addSiteDescription: "Ange domänen för webbplatsen du vill övervaka",
    domainPlaceholder: "exempel.se",
    adding: "Lägger till...",
    noSitesYet: "Inga webbplatser ännu",
    noSitesDescription: "Lägg till din första webbplats för att börja övervaka",
    crawlNow: "Crawla nu",
    crawling: "Crawlar...",
    schedule: "Schemalägg",
    domain: "Domän",
    lastCrawl: "Senaste crawl",
    openIssues: "Öppna problem",
    critical: "kritiska",
    total: "totalt",
    visitSite: "Besök webbplats",
    enabled: "Aktiverad",
    notScheduled: "Inte schemalagd",
    never: "Aldrig",
    
    // Landing content in Swedish from previous translation...
    heroPreline: "AI-driven SEO-analys för moderna webbplatser",
    heroTitle1: "Håll din webbplats",
    heroTitle2: "SEO-optimerad",
    heroSubtitle: "Automatisk skanning, AI-prioritering och omfattande rapporter. Allt du behöver för att upprätthålla och förbättra din webbplats SEO-hälsa.",
    heroCtaPrimary: "Starta Gratis Provperiod",
    heroCtaSecondary: "Se Demo",
    featuresTitle: "Allt du behöver för SEO-övervakning",
    featuresSubtitle: "Från automatisk skanning till detaljerade rapporter - vi har alla verktyg du behöver",
    feature1Title: "Automatisk Webbplatsskanning",
    feature1Desc: "Crawlar alla sidor på din webbplats och identifierar SEO-problem automatiskt",
    feature2Title: "Prioriterade Problem",
    feature2Desc: "AI-driven analys som rankar problem efter viktighet och påverkan",
    feature3Title: "Prestandamätningar",
    feature3Desc: "Övervaka Core Web Vitals, sidtid och andra viktiga prestandamätningar",
    feature4Title: "Automatiska Rapporter",
    feature4Desc: "Schemalägg veckovisa eller månatliga PDF-rapporter till kunder",
    feature5Title: "Schemalagda Crawls",
    feature5Desc: "Automatisk övervakning av webbplatsändringar och nya problem",
    feature6Title: "Teamhantering",
    feature6Desc: "Hantera åtkomst för ditt team med roller och behörigheter",
    useCasesTitle: "Perfekt för alla som arbetar med SEO",
    useCasesSubtitle: "Oavsett om du hanterar din egen webbplats eller levererar tjänster till kunder",
    useCase1Title: "För Företag",
    useCase1Desc: "Perfekt för företag som vill ha full kontroll över sin SEO-hälsa",
    useCase1Benefit1: "Identifiera och åtgärda SEO-problem innan de påverkar rankningar",
    useCase1Benefit2: "Övervaka konkurrerande mått som backlinks och domain rating",
    useCase1Benefit3: "Få AI-drivna rekommendationer för förbättringar",
    useCase1Benefit4: "Exportera data för djupare analys",
    useCase1Cta: "Starta Gratis Provperiod",
    useCase2Title: "För Byråer & Konsulter",
    useCase2Desc: "Perfekt för de som levererar SEO-tjänster till flera kunder",
    useCase2Benefit1: "White-label rapporter med din egen branding",
    useCase2Benefit2: "Hantera flera kunders webbplatser från ett konto",
    useCase2Benefit3: "Automatisera repetitiva SEO-uppgifter",
    useCase2Benefit4: "Visa värdet av dina tjänster med detaljerade rapporter",
    useCase2Cta: "Utforska Enterprise",
    pricingTitle: "Välj planen som passar dig",
    pricingSubtitle: "Alla planer inkluderar 14 dagars gratis provperiod. Inget kreditkort krävs.",
    pricingPopular: "Populär",
    pricingPerMonth: "/månad",
    pricingSites: "webbplatser",
    pricingCrawls: "crawls/månad",
    pricingUnlimited: "Obegränsade",
    pricingCtaFree: "Kom igång",
    pricingCtaPaid: "Välj plan",
    ctaTitle: "Redo att optimera din webbplats?",
    ctaSubtitle: "Gå med tusentals företag och byråer som använder Fixlist för att hålla sina webbplatser SEO-optimerade.",
    ctaButton: "Starta Gratis Provperiod Idag",
    ctaNotice: "Inget kreditkort krävs • 14 dagars gratis provperiod • Avbryt när som helst",
    footerCopyright: "Alla rättigheter förbehållna.",
  },
  da: {
    // Navigation
    sites: "Websites",
    analytics: "Analyse",
    reports: "Rapporter",
    templates: "Skabeloner",
    users: "Brugere",
    billing: "Fakturering",
    settings: "Indstillinger",
    login: "Log ind",
    
    // Common
    search: "Søg",
    filter: "Filtrer",
    export: "Eksporter",
    delete: "Slet",
    edit: "Rediger",
    save: "Gem",
    cancel: "Annuller",
    loading: "Indlæser...",
    noResults: "Ingen resultater fundet",
    actions: "Handlinger",
    status: "Status",
    date: "Dato",
    view: "Vis",
    addNew: "Tilføj ny",
    
    // Sites Page
    sitesTitle: "Websites",
    sitesSubtitle: "Administrer og overvåg dine websites",
    addSite: "Tilføj website",
    addSiteTitle: "Tilføj nyt website",
    addSiteDescription: "Indtast domænet for det website, du vil overvåge",
    domainPlaceholder: "eksempel.dk",
    adding: "Tilføjer...",
    noSitesYet: "Ingen websites endnu",
    noSitesDescription: "Tilføj dit første website for at starte overvågning",
    crawlNow: "Crawl nu",
    crawling: "Crawler...",
    schedule: "Planlæg",
    domain: "Domæne",
    lastCrawl: "Sidste crawl",
    openIssues: "Åbne problemer",
    critical: "kritiske",
    total: "i alt",
    visitSite: "Besøg website",
    enabled: "Aktiveret",
    notScheduled: "Ikke planlagt",
    never: "Aldrig",
    
    // Danish landing translations...
    heroPreline: "AI-drevet SEO-analyse til moderne websites",
    heroTitle1: "Hold dit website",
    heroTitle2: "SEO-optimeret",
    heroSubtitle: "Automatisk scanning, AI-prioritering og omfattende rapporter. Alt du behøver for at vedligeholde og forbedre dit websites SEO-sundhed.",
    heroCtaPrimary: "Start Gratis Prøveperiode",
    heroCtaSecondary: "Se Demo",
    featuresTitle: "Alt du behøver til SEO-overvågning",
    featuresSubtitle: "Fra automatisk scanning til detaljerede rapporter - vi har alle de værktøjer du behøver",
    feature1Title: "Automatisk Websitescanning",
    feature1Desc: "Crawler alle sider på dit website og identificerer SEO-problemer automatisk",
    feature2Title: "Prioriterede Problemer",
    feature2Desc: "AI-drevet analyse der rangerer problemer efter vigtighed og indvirkning",
    feature3Title: "Ydeevnemålinger",
    feature3Desc: "Overvåg Core Web Vitals, sidetid og andre vigtige ydeevnemålinger",
    feature4Title: "Automatiske Rapporter",
    feature4Desc: "Planlæg ugentlige eller månedlige PDF-rapporter til kunder",
    feature5Title: "Planlagte Crawls",
    feature5Desc: "Automatisk overvågning af websiteændringer og nye problemer",
    feature6Title: "Teamstyring",
    feature6Desc: "Administrer adgang for dit team med roller og tilladelser",
    useCasesTitle: "Perfekt til alle der arbejder med SEO",
    useCasesSubtitle: "Uanset om du administrerer dit eget website eller leverer tjenester til kunder",
    useCase1Title: "Til Virksomheder",
    useCase1Desc: "Perfekt til virksomheder der ønsker fuld kontrol over deres SEO-sundhed",
    useCase1Benefit1: "Identificer og ret SEO-problemer før de påvirker placeringer",
    useCase1Benefit2: "Overvåg konkurrencedygtige målinger som backlinks og domænevurdering",
    useCase1Benefit3: "Få AI-drevne anbefalinger til forbedringer",
    useCase1Benefit4: "Eksporter data til dybere analyse",
    useCase1Cta: "Start Gratis Prøveperiode",
    useCase2Title: "Til Bureauer & Konsulenter",
    useCase2Desc: "Perfekt til dem der leverer SEO-tjenester til flere kunder",
    useCase2Benefit1: "White-label rapporter med din egen branding",
    useCase2Benefit2: "Administrer flere kunders websites fra én konto",
    useCase2Benefit3: "Automatiser gentagne SEO-opgaver",
    useCase2Benefit4: "Vis værdien af dine tjenester med detaljerede rapporter",
    useCase2Cta: "Udforsk Enterprise",
    pricingTitle: "Vælg planen der passer til dig",
    pricingSubtitle: "Alle planer inkluderer 14 dages gratis prøveperiode. Intet kreditkort påkrævet.",
    pricingPopular: "Populær",
    pricingPerMonth: "/måned",
    pricingSites: "websites",
    pricingCrawls: "crawls/måned",
    pricingUnlimited: "Ubegrænset",
    pricingCtaFree: "Kom i gang",
    pricingCtaPaid: "Vælg plan",
    ctaTitle: "Klar til at optimere dit website?",
    ctaSubtitle: "Slut dig til tusindvis af virksomheder og bureauer der bruger Fixlist til at holde deres websites SEO-optimerede.",
    ctaButton: "Start Gratis Prøveperiode I Dag",
    ctaNotice: "Intet kreditkort påkrævet • 14 dages gratis prøveperiode • Annuller når som helst",
    footerCopyright: "Alle rettigheder forbeholdes.",
  },
  de: {
    // Navigation  
    sites: "Websites",
    analytics: "Analytics",
    reports: "Berichte",
    templates: "Vorlagen",
    users: "Benutzer",
    billing: "Abrechnung",
    settings: "Einstellungen",
    login: "Anmelden",
    
    // Common
    search: "Suchen",
    filter: "Filtern",
    export: "Exportieren",
    delete: "Löschen",
    edit: "Bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    loading: "Lädt...",
    noResults: "Keine Ergebnisse gefunden",
    actions: "Aktionen",
    status: "Status",
    date: "Datum",
    view: "Ansehen",
    addNew: "Neu hinzufügen",
    
    // Sites Page
    sitesTitle: "Websites",
    sitesSubtitle: "Verwalten und überwachen Sie Ihre Websites",
    addSite: "Website hinzufügen",
    addSiteTitle: "Neue Website hinzufügen",
    addSiteDescription: "Geben Sie die Domain der Website ein, die Sie überwachen möchten",
    domainPlaceholder: "beispiel.de",
    adding: "Wird hinzugefügt...",
    noSitesYet: "Noch keine Websites",
    noSitesDescription: "Fügen Sie Ihre erste Website hinzu, um mit der Überwachung zu beginnen",
    crawlNow: "Jetzt crawlen",
    crawling: "Crawlt...",
    schedule: "Planen",
    domain: "Domain",
    lastCrawl: "Letzter Crawl",
    openIssues: "Offene Probleme",
    critical: "kritisch",
    total: "gesamt",
    visitSite: "Website besuchen",
    enabled: "Aktiviert",
    notScheduled: "Nicht geplant",
    never: "Nie",
    
    // German landing translations...
    heroPreline: "KI-gestützte SEO-Analyse für moderne Websites",
    heroTitle1: "Halten Sie Ihre Website",
    heroTitle2: "SEO-optimiert",
    heroSubtitle: "Automatisches Scannen, KI-Priorisierung und umfassende Berichte. Alles, was Sie brauchen, um die SEO-Gesundheit Ihrer Website zu erhalten und zu verbessern.",
    heroCtaPrimary: "Kostenlose Testversion Starten",
    heroCtaSecondary: "Demo Ansehen",
    featuresTitle: "Alles, was Sie für SEO-Überwachung brauchen",
    featuresSubtitle: "Von automatischem Scannen bis zu detaillierten Berichten - wir haben alle Tools, die Sie brauchen",
    feature1Title: "Automatisches Website-Crawling",
    feature1Desc: "Crawlt alle Seiten Ihrer Website und identifiziert automatisch SEO-Probleme",
    feature2Title: "Priorisierte Probleme",
    feature2Desc: "KI-gestützte Analyse, die Probleme nach Wichtigkeit und Auswirkung ordnet",
    feature3Title: "Leistungsmetriken",
    feature3Desc: "Überwachen Sie Core Web Vitals, Ladezeit und andere wichtige Leistungsmetriken",
    feature4Title: "Automatisierte Berichte",
    feature4Desc: "Planen Sie wöchentliche oder monatliche PDF-Berichte für Kunden",
    feature5Title: "Geplante Crawls",
    feature5Desc: "Automatische Überwachung von Website-Änderungen und neuen Problemen",
    feature6Title: "Teamverwaltung",
    feature6Desc: "Verwalten Sie den Zugriff für Ihr Team mit Rollen und Berechtigungen",
    useCasesTitle: "Perfekt für alle, die mit SEO arbeiten",
    useCasesSubtitle: "Egal, ob Sie Ihre eigene Website verwalten oder Dienstleistungen für Kunden erbringen",
    useCase1Title: "Für Unternehmen",
    useCase1Desc: "Perfekt für Unternehmen, die volle Kontrolle über ihre SEO-Gesundheit wollen",
    useCase1Benefit1: "Identifizieren und beheben Sie SEO-Probleme, bevor sie Rankings beeinflussen",
    useCase1Benefit2: "Überwachen Sie Wettbewerbsmetriken wie Backlinks und Domain Rating",
    useCase1Benefit3: "Erhalten Sie KI-gestützte Empfehlungen für Verbesserungen",
    useCase1Benefit4: "Exportieren Sie Daten für tiefere Analysen",
    useCase1Cta: "Kostenlose Testversion Starten",
    useCase2Title: "Für Agenturen & Berater",
    useCase2Desc: "Perfekt für diejenigen, die SEO-Dienstleistungen für mehrere Kunden erbringen",
    useCase2Benefit1: "White-Label-Berichte mit Ihrem eigenen Branding",
    useCase2Benefit2: "Verwalten Sie mehrere Kunden-Websites von einem Konto aus",
    useCase2Benefit3: "Automatisieren Sie sich wiederholende SEO-Aufgaben",
    useCase2Benefit4: "Zeigen Sie den Wert Ihrer Dienstleistungen mit detaillierten Berichten",
    useCase2Cta: "Enterprise Erkunden",
    pricingTitle: "Wählen Sie den Plan, der zu Ihnen passt",
    pricingSubtitle: "Alle Pläne beinhalten eine 14-tägige kostenlose Testversion. Keine Kreditkarte erforderlich.",
    pricingPopular: "Beliebt",
    pricingPerMonth: "/Monat",
    pricingSites: "Websites",
    pricingCrawls: "Crawls/Monat",
    pricingUnlimited: "Unbegrenzt",
    pricingCtaFree: "Loslegen",
    pricingCtaPaid: "Plan Wählen",
    ctaTitle: "Bereit, Ihre Website zu optimieren?",
    ctaSubtitle: "Schließen Sie sich Tausenden von Unternehmen und Agenturen an, die Fixlist verwenden, um ihre Websites SEO-optimiert zu halten.",
    ctaButton: "Kostenlose Testversion Heute Starten",
    ctaNotice: "Keine Kreditkarte erforderlich • 14-tägige kostenlose Testversion • Jederzeit kündbar",
    footerCopyright: "Alle Rechte vorbehalten.",
  },
  fr: {
    // Navigation
    sites: "Sites",
    analytics: "Analytique",
    reports: "Rapports",
    templates: "Modèles",
    users: "Utilisateurs",
    billing: "Facturation",
    settings: "Paramètres",
    login: "Se connecter",
    
    // Common
    search: "Rechercher",
    filter: "Filtrer",
    export: "Exporter",
    delete: "Supprimer",
    edit: "Modifier",
    save: "Enregistrer",
    cancel: "Annuler",
    loading: "Chargement...",
    noResults: "Aucun résultat trouvé",
    actions: "Actions",
    status: "Statut",
    date: "Date",
    view: "Voir",
    addNew: "Ajouter nouveau",
    
    // Sites Page
    sitesTitle: "Sites",
    sitesSubtitle: "Gérez et surveillez vos sites web",
    addSite: "Ajouter un site",
    addSiteTitle: "Ajouter un nouveau site",
    addSiteDescription: "Entrez le domaine du site web que vous souhaitez surveiller",
    domainPlaceholder: "exemple.fr",
    adding: "Ajout en cours...",
    noSitesYet: "Aucun site pour le moment",
    noSitesDescription: "Ajoutez votre premier site web pour commencer la surveillance",
    crawlNow: "Crawler maintenant",
    crawling: "Crawl en cours...",
    schedule: "Planifier",
    domain: "Domaine",
    lastCrawl: "Dernier crawl",
    openIssues: "Problèmes ouverts",
    critical: "critiques",
    total: "total",
    visitSite: "Visiter le site",
    enabled: "Activé",
    notScheduled: "Non planifié",
    never: "Jamais",
    
    // French landing translations...
    heroPreline: "Analyse SEO alimentée par l'IA pour les sites web modernes",
    heroTitle1: "Gardez votre site web",
    heroTitle2: "optimisé pour le SEO",
    heroSubtitle: "Scan automatique, priorisation par IA et rapports complets. Tout ce dont vous avez besoin pour maintenir et améliorer la santé SEO de votre site web.",
    heroCtaPrimary: "Démarrer l'Essai Gratuit",
    heroCtaSecondary: "Voir la Démo",
    featuresTitle: "Tout ce dont vous avez besoin pour la surveillance SEO",
    featuresSubtitle: "Du scan automatique aux rapports détaillés - nous avons tous les outils dont vous avez besoin",
    feature1Title: "Crawl Automatique du Site",
    feature1Desc: "Crawle toutes les pages de votre site web et identifie automatiquement les problèmes SEO",
    feature2Title: "Problèmes Priorisés",
    feature2Desc: "Analyse pilotée par l'IA qui classe les problèmes par importance et impact",
    feature3Title: "Métriques de Performance",
    feature3Desc: "Surveillez les Core Web Vitals, le temps de chargement et d'autres métriques de performance importantes",
    feature4Title: "Rapports Automatisés",
    feature4Desc: "Planifiez des rapports PDF hebdomadaires ou mensuels pour les clients",
    feature5Title: "Crawls Planifiés",
    feature5Desc: "Surveillance automatique des changements de site web et des nouveaux problèmes",
    feature6Title: "Gestion d'Équipe",
    feature6Desc: "Gérez l'accès de votre équipe avec des rôles et des permissions",
    useCasesTitle: "Parfait pour tous ceux qui travaillent avec le SEO",
    useCasesSubtitle: "Que vous gériez votre propre site web ou que vous fournissiez des services aux clients",
    useCase1Title: "Pour les Entreprises",
    useCase1Desc: "Parfait pour les entreprises qui veulent un contrôle total sur leur santé SEO",
    useCase1Benefit1: "Identifiez et corrigez les problèmes SEO avant qu'ils n'affectent les classements",
    useCase1Benefit2: "Surveillez les métriques concurrentielles comme les backlinks et le domain rating",
    useCase1Benefit3: "Obtenez des recommandations basées sur l'IA pour les améliorations",
    useCase1Benefit4: "Exportez les données pour une analyse plus approfondie",
    useCase1Cta: "Démarrer l'Essai Gratuit",
    useCase2Title: "Pour les Agences & Consultants",
    useCase2Desc: "Parfait pour ceux qui fournissent des services SEO à plusieurs clients",
    useCase2Benefit1: "Rapports en marque blanche avec votre propre image de marque",
    useCase2Benefit2: "Gérez plusieurs sites web de clients depuis un seul compte",
    useCase2Benefit3: "Automatisez les tâches SEO répétitives",
    useCase2Benefit4: "Montrez la valeur de vos services avec des rapports détaillés",
    useCase2Cta: "Explorer Enterprise",
    pricingTitle: "Choisissez le plan qui vous convient",
    pricingSubtitle: "Tous les plans incluent un essai gratuit de 14 jours. Aucune carte de crédit requise.",
    pricingPopular: "Populaire",
    pricingPerMonth: "/mois",
    pricingSites: "sites web",
    pricingCrawls: "crawls/mois",
    pricingUnlimited: "Illimité",
    pricingCtaFree: "Commencer",
    pricingCtaPaid: "Choisir le plan",
    ctaTitle: "Prêt à optimiser votre site web ?",
    ctaSubtitle: "Rejoignez des milliers d'entreprises et d'agences qui utilisent Fixlist pour garder leurs sites web optimisés pour le SEO.",
    ctaButton: "Démarrer l'Essai Gratuit Aujourd'hui",
    ctaNotice: "Aucune carte de crédit requise • Essai gratuit de 14 jours • Annulez à tout moment",
    footerCopyright: "Tous droits réservés.",
  },
  es: {
    // Navigation
    sites: "Sitios",
    analytics: "Analítica",
    reports: "Informes",
    templates: "Plantillas",
    users: "Usuarios",
    billing: "Facturación",
    settings: "Configuración",
    login: "Iniciar sesión",
    
    // Common
    search: "Buscar",
    filter: "Filtrar",
    export: "Exportar",
    delete: "Eliminar",
    edit: "Editar",
    save: "Guardar",
    cancel: "Cancelar",
    loading: "Cargando...",
    noResults: "No se encontraron resultados",
    actions: "Acciones",
    status: "Estado",
    date: "Fecha",
    view: "Ver",
    addNew: "Agregar nuevo",
    
    // Sites Page
    sitesTitle: "Sitios",
    sitesSubtitle: "Gestiona y monitorea tus sitios web",
    addSite: "Agregar sitio",
    addSiteTitle: "Agregar nuevo sitio",
    addSiteDescription: "Ingresa el dominio del sitio web que deseas monitorear",
    domainPlaceholder: "ejemplo.es",
    adding: "Agregando...",
    noSitesYet: "Aún no hay sitios",
    noSitesDescription: "Agrega tu primer sitio web para comenzar a monitorear",
    crawlNow: "Rastrear ahora",
    crawling: "Rastreando...",
    schedule: "Programar",
    domain: "Dominio",
    lastCrawl: "Último rastreo",
    openIssues: "Problemas abiertos",
    critical: "críticos",
    total: "total",
    visitSite: "Visitar sitio",
    enabled: "Habilitado",
    notScheduled: "No programado",
    never: "Nunca",
    
    // Spanish landing translations...
    heroPreline: "Análisis SEO impulsado por IA para sitios web modernos",
    heroTitle1: "Mantén tu sitio web",
    heroTitle2: "optimizado para SEO",
    heroSubtitle: "Escaneo automático, priorización por IA e informes completos. Todo lo que necesitas para mantener y mejorar la salud SEO de tu sitio web.",
    heroCtaPrimary: "Iniciar Prueba Gratuita",
    heroCtaSecondary: "Ver Demo",
    featuresTitle: "Todo lo que necesitas para la monitorización SEO",
    featuresSubtitle: "Desde escaneo automático hasta informes detallados - tenemos todas las herramientas que necesitas",
    feature1Title: "Rastreo Automático del Sitio",
    feature1Desc: "Rastrea todas las páginas de tu sitio web e identifica automáticamente problemas SEO",
    feature2Title: "Problemas Priorizados",
    feature2Desc: "Análisis impulsado por IA que clasifica los problemas por importancia e impacto",
    feature3Title: "Métricas de Rendimiento",
    feature3Desc: "Monitorea Core Web Vitals, tiempo de carga y otras métricas de rendimiento importantes",
    feature4Title: "Informes Automatizados",
    feature4Desc: "Programa informes PDF semanales o mensuales para clientes",
    feature5Title: "Rastreos Programados",
    feature5Desc: "Monitorización automática de cambios en el sitio web y nuevos problemas",
    feature6Title: "Gestión de Equipo",
    feature6Desc: "Gestiona el acceso de tu equipo con roles y permisos",
    useCasesTitle: "Perfecto para todos los que trabajan con SEO",
    useCasesSubtitle: "Ya sea que gestiones tu propio sitio web o prestes servicios a clientes",
    useCase1Title: "Para Empresas",
    useCase1Desc: "Perfecto para empresas que quieren control total sobre su salud SEO",
    useCase1Benefit1: "Identifica y corrige problemas SEO antes de que afecten las clasificaciones",
    useCase1Benefit2: "Monitorea métricas competitivas como backlinks y domain rating",
    useCase1Benefit3: "Obtén recomendaciones impulsadas por IA para mejoras",
    useCase1Benefit4: "Exporta datos para análisis más profundos",
    useCase1Cta: "Iniciar Prueba Gratuita",
    useCase2Title: "Para Agencias y Consultores",
    useCase2Desc: "Perfecto para quienes prestan servicios SEO a múltiples clientes",
    useCase2Benefit1: "Informes de marca blanca con tu propia identidad",
    useCase2Benefit2: "Gestiona múltiples sitios web de clientes desde una cuenta",
    useCase2Benefit3: "Automatiza tareas SEO repetitivas",
    useCase2Benefit4: "Muestra el valor de tus servicios con informes detallados",
    useCase2Cta: "Explorar Enterprise",
    pricingTitle: "Elige el plan que se ajuste a ti",
    pricingSubtitle: "Todos los planes incluyen 14 días de prueba gratuita. No se requiere tarjeta de crédito.",
    pricingPopular: "Popular",
    pricingPerMonth: "/mes",
    pricingSites: "sitios web",
    pricingCrawls: "rastreos/mes",
    pricingUnlimited: "Ilimitado",
    pricingCtaFree: "Comenzar",
    pricingCtaPaid: "Elegir plan",
    ctaTitle: "¿Listo para optimizar tu sitio web?",
    ctaSubtitle: "Únete a miles de empresas y agencias que usan Fixlist para mantener sus sitios web optimizados para SEO.",
    ctaButton: "Iniciar Prueba Gratuita Hoy",
    ctaNotice: "No se requiere tarjeta de crédito • 14 días de prueba gratuita • Cancela en cualquier momento",
    footerCopyright: "Todos los derechos reservados.",
  },
};

async function detectLanguageFromIP() {
  try {
    const response = await fetch('https://ipapi.co/json/');
    const data = await response.json();
    const countryCode = data.country_code;
    
    const countryLanguageMap = {
      'NO': 'no', 'SJ': 'no',
      'SE': 'sv',
      'DK': 'da',
      'DE': 'de', 'AT': 'de', 'CH': 'de',
      'FR': 'fr', 'BE': 'fr', 'LU': 'fr',
      'ES': 'es', 'MX': 'es', 'AR': 'es', 'CO': 'es', 'CL': 'es', 'PE': 'es',
    };
    
    return countryLanguageMap[countryCode] || 'en';
  } catch (error) {
    console.error('Failed to detect language:', error);
    return 'en';
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const savedLang = localStorage.getItem('language');
    if (savedLang) {
      setLanguage(savedLang);
      setLoading(false);
    } else {
      detectLanguageFromIP().then(detectedLang => {
        setLanguage(detectedLang);
        localStorage.setItem('language', detectedLang);
        setLoading(false);
      });
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, loading }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}