import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    sites: "Sites",
    analytics: "Analytics",
    reports: "Reports",
    templates: "Templates",
    users: "Users",
    billing: "Billing",
    settings: "Settings",
    login: "Log in",
    
    // Landing - Hero
    heroPreline: "AI-powered SEO analysis for modern websites",
    heroTitle1: "Keep your website",
    heroTitle2: "SEO-optimized",
    heroSubtitle: "Automatic scanning, AI prioritization, and comprehensive reports. Everything you need to maintain and improve your website's SEO health.",
    heroCtaPrimary: "Start Free Trial",
    heroCtaSecondary: "View Demo",
    
    // Landing - Features
    featuresTitle: "Everything you need for SEO monitoring",
    featuresSubtitle: "From automatic scanning to detailed reports - we have all the tools you need",
    
    feature1Title: "Automatic Site Crawling",
    feature1Desc: "Crawls all pages on your website and automatically identifies SEO issues",
    
    feature2Title: "Prioritized Issues",
    feature2Desc: "AI-driven analysis that ranks issues by importance and impact",
    
    feature3Title: "Performance Metrics",
    feature3Desc: "Monitor Core Web Vitals, page speed, and other important performance metrics",
    
    feature4Title: "Automated Reports",
    feature4Desc: "Schedule weekly or monthly PDF reports for clients",
    
    feature5Title: "Scheduled Crawls",
    feature5Desc: "Automatic monitoring of website changes and new issues",
    
    feature6Title: "Team Management",
    feature6Desc: "Manage access for your team with roles and permissions",
    
    // Landing - Use Cases
    useCasesTitle: "Perfect for everyone working with SEO",
    useCasesSubtitle: "Whether you manage your own website or deliver services to clients",
    
    useCase1Title: "For Businesses",
    useCase1Desc: "Perfect for companies that want full control over their SEO health",
    useCase1Benefit1: "Identify and fix SEO issues before they affect rankings",
    useCase1Benefit2: "Monitor competitive metrics like backlinks and domain rating",
    useCase1Benefit3: "Get AI-driven recommendations for improvements",
    useCase1Benefit4: "Export data for deeper analysis",
    useCase1Cta: "Start Free Trial",
    
    useCase2Title: "For Agencies & Consultants",
    useCase2Desc: "Perfect for those delivering SEO services to multiple clients",
    useCase2Benefit1: "White-label reports with your own branding",
    useCase2Benefit2: "Manage multiple client websites from one account",
    useCase2Benefit3: "Automate repetitive SEO tasks",
    useCase2Benefit4: "Show the value of your services with detailed reports",
    useCase2Cta: "Explore Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Choose the plan that fits you",
    pricingSubtitle: "All plans include a 14-day free trial. No credit card required.",
    pricingPopular: "Popular",
    pricingPerMonth: "/month",
    pricingSites: "websites",
    pricingCrawls: "crawls/month",
    pricingUnlimited: "Unlimited",
    pricingCtaFree: "Get started",
    pricingCtaPaid: "Choose plan",
    
    // Landing - Final CTA
    ctaTitle: "Ready to optimize your website?",
    ctaSubtitle: "Join thousands of businesses and agencies using Fixlist to keep their websites SEO-optimized.",
    ctaButton: "Start Free Trial Today",
    ctaNotice: "No credit card required • 14-day free trial • Cancel anytime",
    
    // Landing - Footer
    footerCopyright: "All rights reserved.",
    
    // Sites Page
    sitesTitle: "Sites",
    sitesAddSite: "Add Site",
    sitesNoSites: "No sites yet",
    sitesNoSitesDesc: "Add your first website to start monitoring its SEO health",
    sitesDomain: "Domain",
    sitesSchedule: "Schedule",
    sitesLastCrawl: "Last Crawl",
    sitesIssues: "Issues",
    sitesActions: "Actions",
    sitesScheduleDaily: "Daily",
    sitesScheduleWeekly: "Weekly",
    sitesScheduleMonthly: "Monthly",
    sitesScheduleDisabled: "Disabled",
    sitesStartCrawl: "Start Crawl",
    sitesManageSchedule: "Manage Schedule",
    sitesViewDetails: "View Details",
    sitesDeleteSite: "Delete Site",
    sitesAddSiteDialogTitle: "Add New Site",
    sitesAddSiteDialogDesc: "Enter the domain of the website you want to monitor",
    sitesDomainPlaceholder: "example.com",
    sitesCancel: "Cancel",
    sitesAdd: "Add",
    
    // Site Overview
    siteOverviewBackToSites: "Back to Sites",
    siteOverviewLastCrawled: "Last crawled",
    siteOverviewStartCrawl: "Start New Crawl",
    siteOverviewStartingCrawl: "Starting Crawl...",
    siteOverviewRenderJs: "Render JavaScript (slower, but better for SPAs)",
    siteOverviewCriticalIssues: "Critical Issues",
    siteOverviewHighPriority: "High Priority",
    siteOverviewMediumPriority: "Medium Priority",
    siteOverviewCrawlHistory: "Crawl History",
    siteOverviewCrawls: "crawls",
    siteOverviewAllIssues: "All Issues",
    siteOverviewOpenIssues: "open issues",
    siteOverviewPages: "Pages",
    siteOverviewPagesCrawled: "pages crawled",
    siteOverviewHealthReport: "Health Report",
    siteOverviewViewTrends: "View performance trends",
    siteOverviewCompetitors: "Competitors",
    siteOverviewBenchmark: "Benchmark against rivals",
    siteOverviewCriticalAttention: "Critical Issues Requiring Attention",
    siteOverviewView: "View",
    
    // Issues Page
    issuesTitle: "Issues",
    issuesFound: "issues found",
    issuesFilters: "Filters",
    issuesAllSeverity: "All Severity",
    issuesCritical: "Critical",
    issuesHigh: "High",
    issuesMedium: "Medium",
    issuesAllStatus: "All Status",
    issuesOpen: "Open",
    issuesIgnored: "Ignored",
    issuesFixed: "Fixed",
    issuesAllTypes: "All Types",
    issuesClearFilters: "Clear filters",
    issuesSeverity: "Severity",
    issuesType: "Type",
    issuesUrl: "URL",
    issuesMessage: "Message",
    issuesStatus: "Status",
    issuesNoIssues: "No issues found",
    issuesNoIssuesDesc: "Try adjusting your filters",
    issuesMarkFixed: "Mark as Fixed",
    issuesMarkIgnored: "Mark as Ignored",
    issuesReopen: "Reopen Issue",
    issuesViewOnly: "View only",
    
    // Reports Page
    reportsTitle: "Reports",
    reportsGenerate: "Generate Report",
    reportsGenerating: "Generating...",
    reportsSelectSite: "Select a site",
    reportsAllSites: "All Sites",
    reportsDateRange: "Date Range",
    reportsFrom: "From",
    reportsTo: "To",
    reportsIncludeComparison: "Include comparison with previous period",
    reportsNoReports: "No reports yet",
    reportsNoReportsDesc: "Generate your first report to get started",
    reportsSite: "Site",
    reportsType: "Type",
    reportsPeriod: "Period",
    reportsCreated: "Created",
    reportsSummary: "Summary",
    reportsManual: "Manual",
    reportsScheduled: "Scheduled",
    reportsPages: "pages",
    reportsTotalIssues: "total issues",
    reportsDownload: "Download",
    
    // Analytics Page
    analyticsTitle: "Analytics",
    analyticsSubtitle: "Track SEO performance and trends across your sites",
    analyticsSelectSite: "Select a site",
    analyticsDateRange: "Date range",
    analyticsLast30Days: "Last 30 days",
    analyticsLast90Days: "Last 90 days",
    analyticsLast6Months: "Last 6 months",
    analyticsLast12Months: "Last 12 months",
    analyticsDomainRating: "Domain Rating",
    analyticsBacklinks: "Backlinks",
    analyticsOrganicTraffic: "Organic Traffic",
    analyticsClicks: "Clicks",
    analyticsImpressions: "Impressions",
    
    // Billing Page
    billingTitle: "Billing & Subscription",
    billingCurrentPlan: "Current Plan",
    billingManageBilling: "Manage Billing",
    billingUpgrade: "Upgrade Plan",
    billingDowngrade: "Downgrade",
    billingAvailablePlans: "Available Plans",
    billingMonthly: "Monthly",
    billingPerMonth: "per month",
    billingSelectPlan: "Select Plan",
    
    // Settings Page
    settingsTitle: "Settings",
    settingsAhrefsTitle: "Ahrefs Integration",
    settingsAhrefsApiKey: "Ahrefs API Key",
    settingsAhrefsPlaceholder: "Enter your Ahrefs API key",
    settingsSave: "Save Changes",
    settingsSaving: "Saving...",
    settingsWhyAhrefs: "Why connect Ahrefs?",
    settingsAccessDenied: "Access Denied",
    settingsNoPermission: "You don't have permission to access settings.",
    
    // Common
    commonLoading: "Loading...",
    commonError: "Error",
    commonSuccess: "Success",
    commonDelete: "Delete",
    commonEdit: "Edit",
    commonSave: "Save",
    commonCancel: "Cancel",
    commonBack: "Back",
    commonNext: "Next",
    commonPrevious: "Previous",
    commonSearch: "Search",
    commonFilter: "Filter",
    commonExport: "Export",
    commonImport: "Import",
    commonSettings: "Settings",
  },
  no: {
    // Navigation
    sites: "Nettsteder",
    analytics: "Analyse",
    reports: "Rapporter",
    templates: "Maler",
    users: "Brukere",
    billing: "Fakturering",
    settings: "Innstillinger",
    login: "Logg inn",
    
    // Landing - Hero
    heroPreline: "AI-drevet SEO-analyse for moderne nettsteder",
    heroTitle1: "Hold nettstedet ditt",
    heroTitle2: "SEO-optimalisert",
    heroSubtitle: "Automatisk skanning, AI-prioritering og omfattende rapporter. Alt du trenger for å opprettholde og forbedre SEO-helsen til nettsidene dine.",
    heroCtaPrimary: "Start Gratis Prøveperiode",
    heroCtaSecondary: "Se Demo",
    
    // Landing - Features
    featuresTitle: "Alt du trenger for SEO-overvåking",
    featuresSubtitle: "Fra automatisk skanning til detaljerte rapporter - vi har alle verktøyene du trenger",
    
    feature1Title: "Automatisk Nettstedskanning",
    feature1Desc: "Crawler alle sidene på nettstedet ditt og identifiserer SEO-problemer automatisk",
    
    feature2Title: "Prioriterte Problemer",
    feature2Desc: "AI-drevet analyse som rangerer problemer etter viktighet og påvirkning",
    
    feature3Title: "Performance Metrics",
    feature3Desc: "Overvåk Core Web Vitals, sidetid, og andre viktige ytelsesmetrikker",
    
    feature4Title: "Automatiske Rapporter",
    feature4Desc: "Planlegg ukentlige eller månedlige PDF-rapporter til kunder",
    
    feature5Title: "Planlagte Crawls",
    feature5Desc: "Automatisk overvåking av nettsted-endringer og nye problemer",
    
    feature6Title: "Team Management",
    feature6Desc: "Administrer tilganger for teamet ditt med roller og tillatelser",
    
    // Landing - Use Cases
    useCasesTitle: "Perfekt for alle som arbeider med SEO",
    useCasesSubtitle: "Uansett om du administrerer ditt eget nettsted eller leverer tjenester til kunder",
    
    useCase1Title: "For Bedrifter",
    useCase1Desc: "Perfekt for bedrifter som vil ha full kontroll over sin SEO-helse",
    useCase1Benefit1: "Identifiser og fiks SEO-problemer før de påvirker rangeringer",
    useCase1Benefit2: "Overvåk konkurransedyktige metrics som backlinks og domain rating",
    useCase1Benefit3: "Få AI-drevne anbefalinger for forbedringer",
    useCase1Benefit4: "Eksporter data for dypere analyse",
    useCase1Cta: "Start Gratis Prøveperiode",
    
    useCase2Title: "For Byråer & Konsulenter",
    useCase2Desc: "Perfekt for de som leverer SEO-tjenester til flere kunder",
    useCase2Benefit1: "White-label rapporter med din egen branding",
    useCase2Benefit2: "Håndter flere kunders nettsteder fra én konto",
    useCase2Benefit3: "Automatiser repeterende SEO-oppgaver",
    useCase2Benefit4: "Vis verdien av dine tjenester med detaljerte rapporter",
    useCase2Cta: "Utforsk Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Velg planen som passer deg",
    pricingSubtitle: "Alle planer inkluderer 14 dagers gratis prøveperiode. Ingen kredittkort nødvendig.",
    pricingPopular: "Populær",
    pricingPerMonth: "/måned",
    pricingSites: "nettsteder",
    pricingCrawls: "crawls/måned",
    pricingUnlimited: "Ubegrensede",
    pricingCtaFree: "Kom i gang",
    pricingCtaPaid: "Velg plan",
    
    // Landing - Final CTA
    ctaTitle: "Klar til å optimalisere nettstedet ditt?",
    ctaSubtitle: "Bli med tusenvis av bedrifter og byråer som bruker Fixlist for å holde nettstedene sine SEO-optimaliserte.",
    ctaButton: "Start Gratis Prøveperiode i dag",
    ctaNotice: "Ingen kredittkort nødvendig • 14 dagers gratis prøveperiode • Avbryt når som helst",
    
    // Landing - Footer
    footerCopyright: "Alle rettigheter forbeholdt.",
    
    // Sites Page
    sitesTitle: "Nettsteder",
    sitesAddSite: "Legg til nettsted",
    sitesNoSites: "Ingen nettsteder ennå",
    sitesNoSitesDesc: "Legg til ditt første nettsted for å begynne å overvåke SEO-helsen",
    sitesDomain: "Domene",
    sitesSchedule: "Tidsplan",
    sitesLastCrawl: "Siste crawl",
    sitesIssues: "Problemer",
    sitesActions: "Handlinger",
    sitesScheduleDaily: "Daglig",
    sitesScheduleWeekly: "Ukentlig",
    sitesScheduleMonthly: "Månedlig",
    sitesScheduleDisabled: "Deaktivert",
    sitesStartCrawl: "Start crawl",
    sitesManageSchedule: "Administrer tidsplan",
    sitesViewDetails: "Vis detaljer",
    sitesDeleteSite: "Slett nettsted",
    sitesAddSiteDialogTitle: "Legg til nytt nettsted",
    sitesAddSiteDialogDesc: "Skriv inn domenet til nettstedet du vil overvåke",
    sitesDomainPlaceholder: "eksempel.no",
    sitesCancel: "Avbryt",
    sitesAdd: "Legg til",
    
    // Site Overview
    siteOverviewBackToSites: "Tilbake til nettsteder",
    siteOverviewLastCrawled: "Sist crawlet",
    siteOverviewStartCrawl: "Start ny crawl",
    siteOverviewStartingCrawl: "Starter crawl...",
    siteOverviewRenderJs: "Render JavaScript (langsommere, men bedre for SPA-er)",
    siteOverviewCriticalIssues: "Kritiske problemer",
    siteOverviewHighPriority: "Høy prioritet",
    siteOverviewMediumPriority: "Middels prioritet",
    siteOverviewCrawlHistory: "Crawl-historikk",
    siteOverviewCrawls: "crawls",
    siteOverviewAllIssues: "Alle problemer",
    siteOverviewOpenIssues: "åpne problemer",
    siteOverviewPages: "Sider",
    siteOverviewPagesCrawled: "sider crawlet",
    siteOverviewHealthReport: "Helserapport",
    siteOverviewViewTrends: "Se ytelsestrender",
    siteOverviewCompetitors: "Konkurrenter",
    siteOverviewBenchmark: "Sammenlign med rivaler",
    siteOverviewCriticalAttention: "Kritiske problemer som krever oppmerksomhet",
    siteOverviewView: "Vis",
    
    // Issues Page
    issuesTitle: "Problemer",
    issuesFound: "problemer funnet",
    issuesFilters: "Filtre",
    issuesAllSeverity: "All alvorlighet",
    issuesCritical: "Kritisk",
    issuesHigh: "Høy",
    issuesMedium: "Middels",
    issuesAllStatus: "All status",
    issuesOpen: "Åpen",
    issuesIgnored: "Ignorert",
    issuesFixed: "Fikset",
    issuesAllTypes: "Alle typer",
    issuesClearFilters: "Fjern filtre",
    issuesSeverity: "Alvorlighet",
    issuesType: "Type",
    issuesUrl: "URL",
    issuesMessage: "Melding",
    issuesStatus: "Status",
    issuesNoIssues: "Ingen problemer funnet",
    issuesNoIssuesDesc: "Prøv å justere filtrene dine",
    issuesMarkFixed: "Merk som fikset",
    issuesMarkIgnored: "Merk som ignorert",
    issuesReopen: "Gjenåpne problem",
    issuesViewOnly: "Kun visning",
    
    // Reports Page
    reportsTitle: "Rapporter",
    reportsSubtitle: "Generer og last ned SEO-rapporter",
    reportsGenerate: "Generer rapport",
    reportsGenerateDesc: "Opprett en omfattende SEO-rapport inkludert problemanalyse, trender og anbefalinger",
    reportsGenerating: "Genererer...",
    reportsSelectSite: "Velg et nettsted",
    reportsAllSites: "Alle nettsteder",
    reportsDateRange: "Datoområde",
    reportsFrom: "Fra",
    reportsTo: "Til",
    reportsLast7Days: "Siste 7 dager",
    reportsLast30Days: "Siste 30 dager",
    reportsLast90Days: "Siste 90 dager",
    reportsIncludeComparison: "Inkluder sammenligning med forrige periode",
    reportsNoReports: "Ingen rapporter ennå",
    reportsNoReportsDesc: "Generer din første rapport for å komme i gang",
    reportsPreviousReports: "Tidligere rapporter",
    reportsReport: "Rapport",
    reportsSite: "Nettsted",
    reportsType: "Type",
    reportsPeriod: "Periode",
    reportsCreated: "Opprettet",
    reportsGenerated: "Generert",
    reportsSummary: "Sammendrag",
    reportsManual: "Manuell",
    reportsScheduled: "Planlagt",
    reportsPages: "sider",
    reportsTotalIssues: "totale problemer",
    reportsDownload: "Last ned",
    
    // Analytics Page
    analyticsTitle: "Analyse",
    analyticsSubtitle: "Spor SEO-ytelse og trender på tvers av nettstedene dine",
    analyticsSelectSite: "Velg et nettsted",
    analyticsAllSites: "Alle nettsteder",
    analyticsDateRange: "Datoområde",
    analyticsLast7Days: "Siste 7 dager",
    analyticsLast30Days: "Siste 30 dager",
    analyticsLast90Days: "Siste 90 dager",
    analyticsAllTime: "All tid",
    analyticsLast6Months: "Siste 6 måneder",
    analyticsLast12Months: "Siste 12 måneder",
    analyticsDomainRating: "Domenevurdering",
    analyticsBacklinks: "Backlinks",
    analyticsTotalClicks: "Totale klikk",
    analyticsOrganicTraffic: "Organisk trafikk",
    analyticsOrganicTrends: "Organisk trafikktrend",
    analyticsIssuesTrend: "Problemtrend over tid",
    analyticsCrawlActivity: "Crawl-aktivitet over tid",
    analyticsNoCrawlData: "Ingen crawl-data tilgjengelig",
    analyticsIssueSeverity: "Problemalvorlighetsfordeling",
    analyticsTopIssueTypes: "Topp problemtyper",
    analyticsHttpCodes: "HTTP-statuskoder",
    analyticsNoPageData: "Ingen sidedata tilgjengelig",
    analyticsSiteComparison: "Nettstedssammenligning",
    analyticsTopQueries: "Topp søkeord",
    analyticsQuery: "Søkeord",
    analyticsClicks: "Klikk",
    analyticsImpressions: "Visninger",
    analyticsCTR: "CTR",
    analyticsPosition: "Posisjon",
    analyticsTopPages: "Topp presterende sider",
    
    // Billing Page
    billingTitle: "Fakturering & Abonnement",
    billingSubtitle: "Administrer ditt abonnement og fakturering",
    billingCurrentPlan: "Gjeldende plan",
    billingTrial: "Prøveperiode",
    billingPastDue: "Forfalt",
    billingManageBilling: "Administrer fakturering",
    billingUpgrade: "Oppgrader",
    billingDowngrade: "Nedgrader",
    billingChoosePlan: "Velg din plan",
    billingDefaultPlan: "Standard plan",
    billingAdminOnly: "Kun administratorer kan administrere fakturering.",
    billingAvailablePlans: "Tilgjengelige planer",
    billingMonthly: "Månedlig",
    billingPerMonth: "per måned",
    billingSelectPlan: "Velg plan",
    
    // Settings Page
    settingsTitle: "Innstillinger",
    settingsSubtitle: "Koble til dine SEO-verktøy for forbedret rapportering",
    settingsAhrefsTitle: "Ahrefs",
    settingsAhrefsDesc: "Skriv inn din Ahrefs API-nøkkel for å hente backlinks, domene rating og henvisende domener data",
    settingsAhrefsApiKey: "API-nøkkel",
    settingsAhrefsPlaceholder: "Skriv inn din Ahrefs API-nøkkel",
    settingsSave: "Lagre API-nøkkel",
    settingsSaving: "Lagrer...",
    settingsWhyAhrefs: "Hvorfor koble til Ahrefs?",
    settingsContactAdmin: "Kontakt en administrator for tilgang.",
    settingsAccessDenied: "Tilgang nektet",
    settingsNoPermission: "Du har ikke tillatelse til å få tilgang til innstillinger.",
    
    // Common
    commonLoading: "Laster...",
    commonError: "Feil",
    commonSuccess: "Suksess",
    commonDelete: "Slett",
    commonEdit: "Rediger",
    commonSave: "Lagre",
    commonCancel: "Avbryt",
    commonBack: "Tilbake",
    commonNext: "Neste",
    commonPrevious: "Forrige",
    commonSearch: "Søk",
    commonFilter: "Filter",
    commonExport: "Eksporter",
    commonImport: "Importer",
    commonSettings: "Innstillinger",
  },
  sv: {
    // Navigation
    sites: "Webbplatser",
    analytics: "Analys",
    reports: "Rapporter",
    templates: "Mallar",
    users: "Användare",
    billing: "Fakturering",
    settings: "Inställningar",
    login: "Logga in",
    
    // Landing - Hero
    heroPreline: "AI-driven SEO-analys för moderna webbplatser",
    heroTitle1: "Håll din webbplats",
    heroTitle2: "SEO-optimerad",
    heroSubtitle: "Automatisk skanning, AI-prioritering och omfattande rapporter. Allt du behöver för att upprätthålla och förbättra din webbplats SEO-hälsa.",
    heroCtaPrimary: "Starta Gratis Provperiod",
    heroCtaSecondary: "Se Demo",
    
    // Landing - Features
    featuresTitle: "Allt du behöver för SEO-övervakning",
    featuresSubtitle: "Från automatisk skanning till detaljerade rapporter - vi har alla verktyg du behöver",
    
    feature1Title: "Automatisk Webbplatsskanning",
    feature1Desc: "Crawlar alla sidor på din webbplats och identifierar SEO-problem automatiskt",
    
    feature2Title: "Prioriterade Problem",
    feature2Desc: "AI-driven analys som rankar problem efter viktighet och påverkan",
    
    feature3Title: "Prestandamätningar",
    feature3Desc: "Övervaka Core Web Vitals, sidtid och andra viktiga prestandamätningar",
    
    feature4Title: "Automatiska Rapporter",
    feature4Desc: "Schemalägg veckovisa eller månatliga PDF-rapporter till kunder",
    
    feature5Title: "Schemalagda Crawls",
    feature5Desc: "Automatisk övervakning av webbplatsändringar och nya problem",
    
    feature6Title: "Teamhantering",
    feature6Desc: "Hantera åtkomst för ditt team med roller och behörigheter",
    
    // Landing - Use Cases
    useCasesTitle: "Perfekt för alla som arbetar med SEO",
    useCasesSubtitle: "Oavsett om du hanterar din egen webbplats eller levererar tjänster till kunder",
    
    useCase1Title: "För Företag",
    useCase1Desc: "Perfekt för företag som vill ha full kontroll över sin SEO-hälsa",
    useCase1Benefit1: "Identifiera och åtgärda SEO-problem innan de påverkar rankningar",
    useCase1Benefit2: "Övervaka konkurrerande mått som backlinks och domain rating",
    useCase1Benefit3: "Få AI-drivna rekommendationer för förbättringar",
    useCase1Benefit4: "Exportera data för djupare analys",
    useCase1Cta: "Starta Gratis Provperiod",
    
    useCase2Title: "För Byråer & Konsulter",
    useCase2Desc: "Perfekt för de som levererar SEO-tjänster till flera kunder",
    useCase2Benefit1: "White-label rapporter med din egen branding",
    useCase2Benefit2: "Hantera flera kunders webbplatser från ett konto",
    useCase2Benefit3: "Automatisera repetitiva SEO-uppgifter",
    useCase2Benefit4: "Visa värdet av dina tjänster med detaljerade rapporter",
    useCase2Cta: "Utforska Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Välj planen som passar dig",
    pricingSubtitle: "Alla planer inkluderar 14 dagars gratis provperiod. Inget kreditkort krävs.",
    pricingPopular: "Populär",
    pricingPerMonth: "/månad",
    pricingSites: "webbplatser",
    pricingCrawls: "crawls/månad",
    pricingUnlimited: "Obegränsade",
    pricingCtaFree: "Kom igång",
    pricingCtaPaid: "Välj plan",
    
    // Landing - Final CTA
    ctaTitle: "Redo att optimera din webbplats?",
    ctaSubtitle: "Gå med tusentals företag och byråer som använder Fixlist för att hålla sina webbplatser SEO-optimerade.",
    ctaButton: "Starta Gratis Provperiod Idag",
    ctaNotice: "Inget kreditkort krävs • 14 dagars gratis provperiod • Avbryt när som helst",
    
    // Landing - Footer
    footerCopyright: "Alla rättigheter förbehållna.",
    
    // Sites Page
    sitesTitle: "Webbplatser",
    sitesAddSite: "Lägg till webbplats",
    sitesNoSites: "Inga webbplatser än",
    sitesNoSitesDesc: "Lägg till din första webbplats för att börja övervaka",
    sitesDomain: "Domän",
    sitesSchedule: "Schema",
    sitesLastCrawl: "Senaste crawl",
    sitesIssues: "Problem",
    sitesActions: "Åtgärder",
    sitesScheduleDaily: "Dagligen",
    sitesScheduleWeekly: "Veckovis",
    sitesScheduleMonthly: "Månadsvis",
    sitesScheduleDisabled: "Inaktiverad",
    sitesStartCrawl: "Starta crawl",
    sitesManageSchedule: "Hantera schema",
    sitesViewDetails: "Visa detaljer",
    sitesDeleteSite: "Ta bort webbplats",
    sitesAddSiteDialogTitle: "Lägg till ny webbplats",
    sitesAddSiteDialogDesc: "Ange domänen för webbplatsen du vill övervaka",
    sitesDomainPlaceholder: "exempel.se",
    sitesCancel: "Avbryt",
    sitesAdd: "Lägg till",
    
    // Site Overview
    siteOverviewBackToSites: "Tillbaka till webbplatser",
    siteOverviewLastCrawled: "Senast crawlad",
    siteOverviewStartCrawl: "Starta ny crawl",
    siteOverviewStartingCrawl: "Startar crawl...",
    siteOverviewRenderJs: "Rendera JavaScript (långsammare, men bättre för SPA-er)",
    siteOverviewCriticalIssues: "Kritiska problem",
    siteOverviewHighPriority: "Hög prioritet",
    siteOverviewMediumPriority: "Medel prioritet",
    siteOverviewCrawlHistory: "Crawl-historik",
    siteOverviewCrawls: "crawls",
    siteOverviewAllIssues: "Alla problem",
    siteOverviewOpenIssues: "öppna problem",
    siteOverviewPages: "Sidor",
    siteOverviewPagesCrawled: "sidor crawlade",
    siteOverviewHealthReport: "Hälsorapport",
    siteOverviewViewTrends: "Visa prestandatrender",
    siteOverviewCompetitors: "Konkurrenter",
    siteOverviewBenchmark: "Jämför med konkurrenter",
    siteOverviewCriticalAttention: "Kritiska problem som kräver uppmärksamhet",
    siteOverviewView: "Visa",
    
    // Issues Page
    issuesTitle: "Problem",
    issuesFound: "problem hittade",
    issuesFilters: "Filter",
    issuesAllSeverity: "All allvarlighetsgrad",
    issuesCritical: "Kritisk",
    issuesHigh: "Hög",
    issuesMedium: "Medel",
    issuesAllStatus: "All status",
    issuesOpen: "Öppen",
    issuesIgnored: "Ignorerad",
    issuesFixed: "Åtgärdad",
    issuesAllTypes: "Alla typer",
    issuesClearFilters: "Rensa filter",
    issuesSeverity: "Allvarlighetsgrad",
    issuesType: "Typ",
    issuesUrl: "URL",
    issuesMessage: "Meddelande",
    issuesStatus: "Status",
    issuesNoIssues: "Inga problem hittade",
    issuesNoIssuesDesc: "Försök justera dina filter",
    issuesMarkFixed: "Markera som åtgärdad",
    issuesMarkIgnored: "Markera som ignorerad",
    issuesReopen: "Återöppna problem",
    issuesViewOnly: "Endast visning",
    
    // Reports Page
    reportsTitle: "Rapporter",
    reportsGenerate: "Generera rapport",
    reportsGenerating: "Genererar...",
    reportsSelectSite: "Välj en webbplats",
    reportsAllSites: "Alla webbplatser",
    reportsDateRange: "Datumintervall",
    reportsFrom: "Från",
    reportsTo: "Till",
    reportsIncludeComparison: "Inkludera jämförelse med föregående period",
    reportsNoReports: "Inga rapporter än",
    reportsNoReportsDesc: "Generera din första rapport för att komma igång",
    reportsSite: "Webbplats",
    reportsType: "Typ",
    reportsPeriod: "Period",
    reportsCreated: "Skapad",
    reportsSummary: "Sammanfattning",
    reportsManual: "Manuell",
    reportsScheduled: "Schemalagd",
    reportsPages: "sidor",
    reportsTotalIssues: "totala problem",
    reportsDownload: "Ladda ner",
    
    // Analytics Page
    analyticsTitle: "Analys",
    analyticsSubtitle: "Spåra SEO-prestanda och trender över dina webbplatser",
    analyticsSelectSite: "Välj en webbplats",
    analyticsDateRange: "Datumintervall",
    analyticsLast30Days: "Senaste 30 dagarna",
    analyticsLast90Days: "Senaste 90 dagarna",
    analyticsLast6Months: "Senaste 6 månaderna",
    analyticsLast12Months: "Senaste 12 månaderna",
    analyticsDomainRating: "Domänbetyg",
    analyticsBacklinks: "Backlinks",
    analyticsOrganicTraffic: "Organisk trafik",
    analyticsClicks: "Klick",
    analyticsImpressions: "Visningar",
    
    // Billing Page
    billingTitle: "Fakturering & Prenumeration",
    billingCurrentPlan: "Nuvarande plan",
    billingManageBilling: "Hantera fakturering",
    billingUpgrade: "Uppgradera plan",
    billingDowngrade: "Nedgradera",
    billingAvailablePlans: "Tillgängliga planer",
    billingMonthly: "Månadsvis",
    billingPerMonth: "per månad",
    billingSelectPlan: "Välj plan",
    
    // Settings Page
    settingsTitle: "Inställningar",
    settingsAhrefsTitle: "Ahrefs-integration",
    settingsAhrefsApiKey: "Ahrefs API-nyckel",
    settingsAhrefsPlaceholder: "Ange din Ahrefs API-nyckel",
    settingsSave: "Spara ändringar",
    settingsSaving: "Sparar...",
    settingsWhyAhrefs: "Varför ansluta Ahrefs?",
    settingsAccessDenied: "Åtkomst nekad",
    settingsNoPermission: "Du har inte behörighet att komma åt inställningar.",
    
    // Common
    commonLoading: "Laddar...",
    commonError: "Fel",
    commonSuccess: "Framgång",
    commonDelete: "Ta bort",
    commonEdit: "Redigera",
    commonSave: "Spara",
    commonCancel: "Avbryt",
    commonBack: "Tillbaka",
    commonNext: "Nästa",
    commonPrevious: "Föregående",
    commonSearch: "Sök",
    commonFilter: "Filter",
    commonExport: "Exportera",
    commonImport: "Importera",
    commonSettings: "Inställningar",
  },
  da: {
    // Navigation
    sites: "Websites",
    analytics: "Analyse",
    reports: "Rapporter",
    templates: "Skabeloner",
    users: "Brugere",
    billing: "Fakturering",
    settings: "Indstillinger",
    login: "Log ind",
    
    // Landing - Hero
    heroPreline: "AI-drevet SEO-analyse til moderne websites",
    heroTitle1: "Hold dit website",
    heroTitle2: "SEO-optimeret",
    heroSubtitle: "Automatisk scanning, AI-prioritering og omfattende rapporter. Alt du behøver for at vedligeholde og forbedre dit websites SEO-sundhed.",
    heroCtaPrimary: "Start Gratis Prøveperiode",
    heroCtaSecondary: "Se Demo",
    
    // Landing - Features
    featuresTitle: "Alt du behøver til SEO-overvågning",
    featuresSubtitle: "Fra automatisk scanning til detaljerede rapporter - vi har alle de værktøjer du behøver",
    
    feature1Title: "Automatisk Websitescanning",
    feature1Desc: "Crawler alle sider på dit website og identificerer SEO-problemer automatisk",
    
    feature2Title: "Prioriterede Problemer",
    feature2Desc: "AI-drevet analyse der rangerer problemer efter vigtighed og indvirkning",
    
    feature3Title: "Ydeevnemålinger",
    feature3Desc: "Overvåg Core Web Vitals, sidetid og andre vigtige ydeevnemålinger",
    
    feature4Title: "Automatiske Rapporter",
    feature4Desc: "Planlæg ugentlige eller månedlige PDF-rapporter til kunder",
    
    feature5Title: "Planlagte Crawls",
    feature5Desc: "Automatisk overvågning af websiteændringer og nye problemer",
    
    feature6Title: "Teamstyring",
    feature6Desc: "Administrer adgang for dit team med roller og tilladelser",
    
    // Landing - Use Cases
    useCasesTitle: "Perfekt til alle der arbejder med SEO",
    useCasesSubtitle: "Uanset om du administrerer dit eget website eller leverer tjenester til kunder",
    
    useCase1Title: "Til Virksomheder",
    useCase1Desc: "Perfekt til virksomheder der ønsker fuld kontrol over deres SEO-sundhed",
    useCase1Benefit1: "Identificer og ret SEO-problemer før de påvirker placeringer",
    useCase1Benefit2: "Overvåg konkurrencedygtige målinger som backlinks og domænevurdering",
    useCase1Benefit3: "Få AI-drevne anbefalinger til forbedringer",
    useCase1Benefit4: "Eksporter data til dybere analyse",
    useCase1Cta: "Start Gratis Prøveperiode",
    
    useCase2Title: "Til Bureauer & Konsulenter",
    useCase2Desc: "Perfekt til dem der leverer SEO-tjenester til flere kunder",
    useCase2Benefit1: "White-label rapporter med din egen branding",
    useCase2Benefit2: "Administrer flere kunders websites fra én konto",
    useCase2Benefit3: "Automatiser gentagne SEO-opgaver",
    useCase2Benefit4: "Vis værdien af dine tjenester med detaljerede rapporter",
    useCase2Cta: "Udforsk Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Vælg planen der passer til dig",
    pricingSubtitle: "Alle planer inkluderer 14 dages gratis prøveperiode. Intet kreditkort påkrævet.",
    pricingPopular: "Populær",
    pricingPerMonth: "/måned",
    pricingSites: "websites",
    pricingCrawls: "crawls/måned",
    pricingUnlimited: "Ubegrænset",
    pricingCtaFree: "Kom i gang",
    pricingCtaPaid: "Vælg plan",
    
    // Landing - Final CTA
    ctaTitle: "Klar til at optimere dit website?",
    ctaSubtitle: "Slut dig til tusindvis af virksomheder og bureauer der bruger Fixlist til at holde deres websites SEO-optimerede.",
    ctaButton: "Start Gratis Prøveperiode I Dag",
    ctaNotice: "Intet kreditkort påkrævet • 14 dages gratis prøveperiode • Annuller når som helst",
    
    // Landing - Footer
    footerCopyright: "Alle rettigheder forbeholdes.",
    
    // Sites Page
    sitesTitle: "Websites",
    sitesAddSite: "Tilføj website",
    sitesNoSites: "Ingen websites endnu",
    sitesNoSitesDesc: "Tilføj dit første website for at begynde at overvåge",
    sitesDomain: "Domæne",
    sitesSchedule: "Tidsplan",
    sitesLastCrawl: "Sidste crawl",
    sitesIssues: "Problemer",
    sitesActions: "Handlinger",
    sitesScheduleDaily: "Dagligt",
    sitesScheduleWeekly: "Ugentligt",
    sitesScheduleMonthly: "Månedligt",
    sitesScheduleDisabled: "Deaktiveret",
    sitesStartCrawl: "Start crawl",
    sitesManageSchedule: "Administrer tidsplan",
    sitesViewDetails: "Vis detaljer",
    sitesDeleteSite: "Slet website",
    sitesAddSiteDialogTitle: "Tilføj nyt website",
    sitesAddSiteDialogDesc: "Indtast domænet for det website du vil overvåge",
    sitesDomainPlaceholder: "eksempel.dk",
    sitesCancel: "Annuller",
    sitesAdd: "Tilføj",
    
    // Site Overview
    siteOverviewBackToSites: "Tilbage til websites",
    siteOverviewLastCrawled: "Sidst crawlet",
    siteOverviewStartCrawl: "Start ny crawl",
    siteOverviewStartingCrawl: "Starter crawl...",
    siteOverviewRenderJs: "Render JavaScript (langsommere, men bedre for SPA'er)",
    siteOverviewCriticalIssues: "Kritiske problemer",
    siteOverviewHighPriority: "Høj prioritet",
    siteOverviewMediumPriority: "Mellem prioritet",
    siteOverviewCrawlHistory: "Crawl-historik",
    siteOverviewCrawls: "crawls",
    siteOverviewAllIssues: "Alle problemer",
    siteOverviewOpenIssues: "åbne problemer",
    siteOverviewPages: "Sider",
    siteOverviewPagesCrawled: "sider crawlet",
    siteOverviewHealthReport: "Sundhedsrapport",
    siteOverviewViewTrends: "Vis ydeevnetendenser",
    siteOverviewCompetitors: "Konkurrenter",
    siteOverviewBenchmark: "Benchmark mod konkurrenter",
    siteOverviewCriticalAttention: "Kritiske problemer der kræver opmærksomhed",
    siteOverviewView: "Vis",
    
    // Issues Page
    issuesTitle: "Problemer",
    issuesFound: "problemer fundet",
    issuesFilters: "Filtre",
    issuesAllSeverity: "Al sværhedsgrad",
    issuesCritical: "Kritisk",
    issuesHigh: "Høj",
    issuesMedium: "Mellem",
    issuesAllStatus: "Al status",
    issuesOpen: "Åben",
    issuesIgnored: "Ignoreret",
    issuesFixed: "Rettet",
    issuesAllTypes: "Alle typer",
    issuesClearFilters: "Ryd filtre",
    issuesSeverity: "Sværhedsgrad",
    issuesType: "Type",
    issuesUrl: "URL",
    issuesMessage: "Besked",
    issuesStatus: "Status",
    issuesNoIssues: "Ingen problemer fundet",
    issuesNoIssuesDesc: "Prøv at justere dine filtre",
    issuesMarkFixed: "Marker som rettet",
    issuesMarkIgnored: "Marker som ignoreret",
    issuesReopen: "Genåbn problem",
    issuesViewOnly: "Kun visning",
    
    // Reports Page
    reportsTitle: "Rapporter",
    reportsGenerate: "Generer rapport",
    reportsGenerating: "Genererer...",
    reportsSelectSite: "Vælg et website",
    reportsAllSites: "Alle websites",
    reportsDateRange: "Datointerval",
    reportsFrom: "Fra",
    reportsTo: "Til",
    reportsIncludeComparison: "Inkluder sammenligning med forrige periode",
    reportsNoReports: "Ingen rapporter endnu",
    reportsNoReportsDesc: "Generer din første rapport for at komme i gang",
    reportsSite: "Website",
    reportsType: "Type",
    reportsPeriod: "Periode",
    reportsCreated: "Oprettet",
    reportsSummary: "Resumé",
    reportsManual: "Manuel",
    reportsScheduled: "Planlagt",
    reportsPages: "sider",
    reportsTotalIssues: "totale problemer",
    reportsDownload: "Download",
    
    // Analytics Page
    analyticsTitle: "Analyse",
    analyticsSubtitle: "Spor SEO-ydeevne og tendenser på tværs af dine websites",
    analyticsSelectSite: "Vælg et website",
    analyticsDateRange: "Datointerval",
    analyticsLast30Days: "Sidste 30 dage",
    analyticsLast90Days: "Sidste 90 dage",
    analyticsLast6Months: "Sidste 6 måneder",
    analyticsLast12Months: "Sidste 12 måneder",
    analyticsDomainRating: "Domænevurdering",
    analyticsBacklinks: "Backlinks",
    analyticsOrganicTraffic: "Organisk trafik",
    analyticsClicks: "Klik",
    analyticsImpressions: "Visninger",
    
    // Billing Page
    billingTitle: "Fakturering & Abonnement",
    billingCurrentPlan: "Nuværende plan",
    billingManageBilling: "Administrer fakturering",
    billingUpgrade: "Opgrader plan",
    billingDowngrade: "Nedgrader",
    billingAvailablePlans: "Tilgængelige planer",
    billingMonthly: "Månedligt",
    billingPerMonth: "per måned",
    billingSelectPlan: "Vælg plan",
    
    // Settings Page
    settingsTitle: "Indstillinger",
    settingsAhrefsTitle: "Ahrefs-integration",
    settingsAhrefsApiKey: "Ahrefs API-nøgle",
    settingsAhrefsPlaceholder: "Indtast din Ahrefs API-nøgle",
    settingsSave: "Gem ændringer",
    settingsSaving: "Gemmer...",
    settingsWhyAhrefs: "Hvorfor tilslutte Ahrefs?",
    settingsAccessDenied: "Adgang nægtet",
    settingsNoPermission: "Du har ikke tilladelse til at få adgang til indstillinger.",
    
    // Common
    commonLoading: "Indlæser...",
    commonError: "Fejl",
    commonSuccess: "Succes",
    commonDelete: "Slet",
    commonEdit: "Rediger",
    commonSave: "Gem",
    commonCancel: "Annuller",
    commonBack: "Tilbage",
    commonNext: "Næste",
    commonPrevious: "Forrige",
    commonSearch: "Søg",
    commonFilter: "Filter",
    commonExport: "Eksporter",
    commonImport: "Importer",
    commonSettings: "Indstillinger",
  },
  de: {
    // Navigation
    sites: "Websites",
    analytics: "Analytics",
    reports: "Berichte",
    templates: "Vorlagen",
    users: "Benutzer",
    billing: "Abrechnung",
    settings: "Einstellungen",
    login: "Anmelden",
    
    // Landing - Hero
    heroPreline: "KI-gestützte SEO-Analyse für moderne Websites",
    heroTitle1: "Halten Sie Ihre Website",
    heroTitle2: "SEO-optimiert",
    heroSubtitle: "Automatisches Scannen, KI-Priorisierung und umfassende Berichte. Alles, was Sie brauchen, um die SEO-Gesundheit Ihrer Website zu erhalten und zu verbessern.",
    heroCtaPrimary: "Kostenlose Testversion Starten",
    heroCtaSecondary: "Demo Ansehen",
    
    // Landing - Features
    featuresTitle: "Alles, was Sie für SEO-Überwachung brauchen",
    featuresSubtitle: "Von automatischem Scannen bis zu detaillierten Berichten - wir haben alle Tools, die Sie brauchen",
    
    feature1Title: "Automatisches Website-Crawling",
    feature1Desc: "Crawlt alle Seiten Ihrer Website und identifiziert automatisch SEO-Probleme",
    
    feature2Title: "Priorisierte Probleme",
    feature2Desc: "KI-gestützte Analyse, die Probleme nach Wichtigkeit und Auswirkung ordnet",
    
    feature3Title: "Leistungsmetriken",
    feature3Desc: "Überwachen Sie Core Web Vitals, Ladezeit und andere wichtige Leistungsmetriken",
    
    feature4Title: "Automatisierte Berichte",
    feature4Desc: "Planen Sie wöchentliche oder monatliche PDF-Berichte für Kunden",
    
    feature5Title: "Geplante Crawls",
    feature5Desc: "Automatische Überwachung von Website-Änderungen und neuen Problemen",
    
    feature6Title: "Teamverwaltung",
    feature6Desc: "Verwalten Sie den Zugriff für Ihr Team mit Rollen und Berechtigungen",
    
    // Landing - Use Cases
    useCasesTitle: "Perfekt für alle, die mit SEO arbeiten",
    useCasesSubtitle: "Egal, ob Sie Ihre eigene Website verwalten oder Dienstleistungen für Kunden erbringen",
    
    useCase1Title: "Für Unternehmen",
    useCase1Desc: "Perfekt für Unternehmen, die volle Kontrolle über ihre SEO-Gesundheit wollen",
    useCase1Benefit1: "Identifizieren und beheben Sie SEO-Probleme, bevor sie Rankings beeinflussen",
    useCase1Benefit2: "Überwachen Sie Wettbewerbsmetriken wie Backlinks und Domain Rating",
    useCase1Benefit3: "Erhalten Sie KI-gestützte Empfehlungen für Verbesserungen",
    useCase1Benefit4: "Exportieren Sie Daten für tiefere Analysen",
    useCase1Cta: "Kostenlose Testversion Starten",
    
    useCase2Title: "Für Agenturen & Berater",
    useCase2Desc: "Perfekt für diejenigen, die SEO-Dienstleistungen für mehrere Kunden erbringen",
    useCase2Benefit1: "White-Label-Berichte mit Ihrem eigenen Branding",
    useCase2Benefit2: "Verwalten Sie mehrere Kunden-Websites von einem Konto aus",
    useCase2Benefit3: "Automatisieren Sie sich wiederholende SEO-Aufgaben",
    useCase2Benefit4: "Zeigen Sie den Wert Ihrer Dienstleistungen mit detaillierten Berichten",
    useCase2Cta: "Enterprise Erkunden",
    
    // Landing - Pricing
    pricingTitle: "Wählen Sie den Plan, der zu Ihnen passt",
    pricingSubtitle: "Alle Pläne beinhalten eine 14-tägige kostenlose Testversion. Keine Kreditkarte erforderlich.",
    pricingPopular: "Beliebt",
    pricingPerMonth: "/Monat",
    pricingSites: "Websites",
    pricingCrawls: "Crawls/Monat",
    pricingUnlimited: "Unbegrenzt",
    pricingCtaFree: "Loslegen",
    pricingCtaPaid: "Plan Wählen",
    
    // Landing - Final CTA
    ctaTitle: "Bereit, Ihre Website zu optimieren?",
    ctaSubtitle: "Schließen Sie sich Tausenden von Unternehmen und Agenturen an, die Fixlist verwenden, um ihre Websites SEO-optimiert zu halten.",
    ctaButton: "Kostenlose Testversion Heute Starten",
    ctaNotice: "Keine Kreditkarte erforderlich • 14-tägige kostenlose Testversion • Jederzeit kündbar",
    
    // Landing - Footer
    footerCopyright: "Alle Rechte vorbehalten.",
    
    // Sites Page
    sitesTitle: "Websites",
    sitesAddSite: "Website hinzufügen",
    sitesNoSites: "Noch keine Websites",
    sitesNoSitesDesc: "Fügen Sie Ihre erste Website hinzu, um mit der Überwachung zu beginnen",
    sitesDomain: "Domain",
    sitesSchedule: "Zeitplan",
    sitesLastCrawl: "Letzter Crawl",
    sitesIssues: "Probleme",
    sitesActions: "Aktionen",
    sitesScheduleDaily: "Täglich",
    sitesScheduleWeekly: "Wöchentlich",
    sitesScheduleMonthly: "Monatlich",
    sitesScheduleDisabled: "Deaktiviert",
    sitesStartCrawl: "Crawl starten",
    sitesManageSchedule: "Zeitplan verwalten",
    sitesViewDetails: "Details anzeigen",
    sitesDeleteSite: "Website löschen",
    sitesAddSiteDialogTitle: "Neue Website hinzufügen",
    sitesAddSiteDialogDesc: "Geben Sie die Domain der Website ein, die Sie überwachen möchten",
    sitesDomainPlaceholder: "beispiel.de",
    sitesCancel: "Abbrechen",
    sitesAdd: "Hinzufügen",
    
    // Site Overview
    siteOverviewBackToSites: "Zurück zu Websites",
    siteOverviewLastCrawled: "Zuletzt gecrawlt",
    siteOverviewStartCrawl: "Neuen Crawl starten",
    siteOverviewStartingCrawl: "Crawl wird gestartet...",
    siteOverviewRenderJs: "JavaScript rendern (langsamer, aber besser für SPAs)",
    siteOverviewCriticalIssues: "Kritische Probleme",
    siteOverviewHighPriority: "Hohe Priorität",
    siteOverviewMediumPriority: "Mittlere Priorität",
    siteOverviewCrawlHistory: "Crawl-Verlauf",
    siteOverviewCrawls: "Crawls",
    siteOverviewAllIssues: "Alle Probleme",
    siteOverviewOpenIssues: "offene Probleme",
    siteOverviewPages: "Seiten",
    siteOverviewPagesCrawled: "Seiten gecrawlt",
    siteOverviewHealthReport: "Zustandsbericht",
    siteOverviewViewTrends: "Leistungstrends anzeigen",
    siteOverviewCompetitors: "Konkurrenten",
    siteOverviewBenchmark: "Benchmark gegen Konkurrenten",
    siteOverviewCriticalAttention: "Kritische Probleme, die Aufmerksamkeit erfordern",
    siteOverviewView: "Anzeigen",
    
    // Issues Page
    issuesTitle: "Probleme",
    issuesFound: "Probleme gefunden",
    issuesFilters: "Filter",
    issuesAllSeverity: "Alle Schweregrade",
    issuesCritical: "Kritisch",
    issuesHigh: "Hoch",
    issuesMedium: "Mittel",
    issuesAllStatus: "Alle Status",
    issuesOpen: "Offen",
    issuesIgnored: "Ignoriert",
    issuesFixed: "Behoben",
    issuesAllTypes: "Alle Typen",
    issuesClearFilters: "Filter löschen",
    issuesSeverity: "Schweregrad",
    issuesType: "Typ",
    issuesUrl: "URL",
    issuesMessage: "Nachricht",
    issuesStatus: "Status",
    issuesNoIssues: "Keine Probleme gefunden",
    issuesNoIssuesDesc: "Versuchen Sie, Ihre Filter anzupassen",
    issuesMarkFixed: "Als behoben markieren",
    issuesMarkIgnored: "Als ignoriert markieren",
    issuesReopen: "Problem wieder öffnen",
    issuesViewOnly: "Nur ansehen",
    
    // Reports Page
    reportsTitle: "Berichte",
    reportsGenerate: "Bericht generieren",
    reportsGenerating: "Wird generiert...",
    reportsSelectSite: "Website auswählen",
    reportsAllSites: "Alle Websites",
    reportsDateRange: "Datumsbereich",
    reportsFrom: "Von",
    reportsTo: "Bis",
    reportsIncludeComparison: "Vergleich mit vorheriger Periode einschließen",
    reportsNoReports: "Noch keine Berichte",
    reportsNoReportsDesc: "Generieren Sie Ihren ersten Bericht, um zu beginnen",
    reportsSite: "Website",
    reportsType: "Typ",
    reportsPeriod: "Zeitraum",
    reportsCreated: "Erstellt",
    reportsSummary: "Zusammenfassung",
    reportsManual: "Manuell",
    reportsScheduled: "Geplant",
    reportsPages: "Seiten",
    reportsTotalIssues: "Gesamtprobleme",
    reportsDownload: "Herunterladen",
    
    // Analytics Page
    analyticsTitle: "Analytics",
    analyticsSubtitle: "Verfolgen Sie SEO-Leistung und Trends über Ihre Websites",
    analyticsSelectSite: "Website auswählen",
    analyticsDateRange: "Datumsbereich",
    analyticsLast30Days: "Letzte 30 Tage",
    analyticsLast90Days: "Letzte 90 Tage",
    analyticsLast6Months: "Letzte 6 Monate",
    analyticsLast12Months: "Letzte 12 Monate",
    analyticsDomainRating: "Domain Rating",
    analyticsBacklinks: "Backlinks",
    analyticsOrganicTraffic: "Organischer Traffic",
    analyticsClicks: "Klicks",
    analyticsImpressions: "Impressionen",
    
    // Billing Page
    billingTitle: "Abrechnung & Abonnement",
    billingCurrentPlan: "Aktueller Plan",
    billingManageBilling: "Abrechnung verwalten",
    billingUpgrade: "Plan upgraden",
    billingDowngrade: "Downgraden",
    billingAvailablePlans: "Verfügbare Pläne",
    billingMonthly: "Monatlich",
    billingPerMonth: "pro Monat",
    billingSelectPlan: "Plan wählen",
    
    // Settings Page
    settingsTitle: "Einstellungen",
    settingsAhrefsTitle: "Ahrefs-Integration",
    settingsAhrefsApiKey: "Ahrefs API-Schlüssel",
    settingsAhrefsPlaceholder: "Geben Sie Ihren Ahrefs API-Schlüssel ein",
    settingsSave: "Änderungen speichern",
    settingsSaving: "Wird gespeichert...",
    settingsWhyAhrefs: "Warum Ahrefs verbinden?",
    settingsAccessDenied: "Zugriff verweigert",
    settingsNoPermission: "Sie haben keine Berechtigung, auf Einstellungen zuzugreifen.",
    
    // Common
    commonLoading: "Lädt...",
    commonError: "Fehler",
    commonSuccess: "Erfolg",
    commonDelete: "Löschen",
    commonEdit: "Bearbeiten",
    commonSave: "Speichern",
    commonCancel: "Abbrechen",
    commonBack: "Zurück",
    commonNext: "Weiter",
    commonPrevious: "Zurück",
    commonSearch: "Suchen",
    commonFilter: "Filter",
    commonExport: "Exportieren",
    commonImport: "Importieren",
    commonSettings: "Einstellungen",
  },
  fr: {
    // Navigation
    sites: "Sites",
    analytics: "Analytique",
    reports: "Rapports",
    templates: "Modèles",
    users: "Utilisateurs",
    billing: "Facturation",
    settings: "Paramètres",
    login: "Se connecter",
    
    // Landing - Hero
    heroPreline: "Analyse SEO alimentée par l'IA pour les sites web modernes",
    heroTitle1: "Gardez votre site web",
    heroTitle2: "optimisé pour le SEO",
    heroSubtitle: "Scan automatique, priorisation par IA et rapports complets. Tout ce dont vous avez besoin pour maintenir et améliorer la santé SEO de votre site web.",
    heroCtaPrimary: "Démarrer l'Essai Gratuit",
    heroCtaSecondary: "Voir la Démo",
    
    // Landing - Features
    featuresTitle: "Tout ce dont vous avez besoin pour la surveillance SEO",
    featuresSubtitle: "Du scan automatique aux rapports détaillés - nous avons tous les outils dont vous avez besoin",
    
    feature1Title: "Crawl Automatique du Site",
    feature1Desc: "Crawle toutes les pages de votre site web et identifie automatiquement les problèmes SEO",
    
    feature2Title: "Problèmes Priorisés",
    feature2Desc: "Analyse pilotée par l'IA qui classe les problèmes par importance et impact",
    
    feature3Title: "Métriques de Performance",
    feature3Desc: "Surveillez les Core Web Vitals, le temps de chargement et d'autres métriques de performance importantes",
    
    feature4Title: "Rapports Automatisés",
    feature4Desc: "Planifiez des rapports PDF hebdomadaires ou mensuels pour les clients",
    
    feature5Title: "Crawls Planifiés",
    feature5Desc: "Surveillance automatique des changements de site web et des nouveaux problèmes",
    
    feature6Title: "Gestion d'Équipe",
    feature6Desc: "Gérez l'accès de votre équipe avec des rôles et des permissions",
    
    // Landing - Use Cases
    useCasesTitle: "Parfait pour tous ceux qui travaillent avec le SEO",
    useCasesSubtitle: "Que vous gériez votre propre site web ou que vous fournissiez des services aux clients",
    
    useCase1Title: "Pour les Entreprises",
    useCase1Desc: "Parfait pour les entreprises qui veulent un contrôle total sur leur santé SEO",
    useCase1Benefit1: "Identifiez et corrigez les problèmes SEO avant qu'ils n'affectent les classements",
    useCase1Benefit2: "Surveillez les métriques concurrentielles comme les backlinks et le domain rating",
    useCase1Benefit3: "Obtenez des recommandations basées sur l'IA pour les améliorations",
    useCase1Benefit4: "Exportez les données pour une analyse plus approfondie",
    useCase1Cta: "Démarrer l'Essai Gratuit",
    
    useCase2Title: "Pour les Agences & Consultants",
    useCase2Desc: "Parfait pour ceux qui fournissent des services SEO à plusieurs clients",
    useCase2Benefit1: "Rapports en marque blanche avec votre propre image de marque",
    useCase2Benefit2: "Gérez plusieurs sites web de clients depuis un seul compte",
    useCase2Benefit3: "Automatisez les tâches SEO répétitives",
    useCase2Benefit4: "Montrez la valeur de vos services avec des rapports détaillés",
    useCase2Cta: "Explorer Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Choisissez le plan qui vous convient",
    pricingSubtitle: "Tous les plans incluent un essai gratuit de 14 jours. Aucune carte de crédit requise.",
    pricingPopular: "Populaire",
    pricingPerMonth: "/mois",
    pricingSites: "sites web",
    pricingCrawls: "crawls/mois",
    pricingUnlimited: "Illimité",
    pricingCtaFree: "Commencer",
    pricingCtaPaid: "Choisir le plan",
    
    // Landing - Final CTA
    ctaTitle: "Prêt à optimiser votre site web ?",
    ctaSubtitle: "Rejoignez des milliers d'entreprises et d'agences qui utilisent Fixlist pour garder leurs sites web optimisés pour le SEO.",
    ctaButton: "Démarrer l'Essai Gratuit Aujourd'hui",
    ctaNotice: "Aucune carte de crédit requise • Essai gratuit de 14 jours • Annulez à tout moment",
    
    // Landing - Footer
    footerCopyright: "Tous droits réservés.",
    
    // Sites Page
    sitesTitle: "Sites",
    sitesAddSite: "Ajouter un site",
    sitesNoSites: "Aucun site pour le moment",
    sitesNoSitesDesc: "Ajoutez votre premier site web pour commencer la surveillance",
    sitesDomain: "Domaine",
    sitesSchedule: "Planification",
    sitesLastCrawl: "Dernier crawl",
    sitesIssues: "Problèmes",
    sitesActions: "Actions",
    sitesScheduleDaily: "Quotidien",
    sitesScheduleWeekly: "Hebdomadaire",
    sitesScheduleMonthly: "Mensuel",
    sitesScheduleDisabled: "Désactivé",
    sitesStartCrawl: "Démarrer le crawl",
    sitesManageSchedule: "Gérer la planification",
    sitesViewDetails: "Voir les détails",
    sitesDeleteSite: "Supprimer le site",
    sitesAddSiteDialogTitle: "Ajouter un nouveau site",
    sitesAddSiteDialogDesc: "Entrez le domaine du site web que vous souhaitez surveiller",
    sitesDomainPlaceholder: "exemple.fr",
    sitesCancel: "Annuler",
    sitesAdd: "Ajouter",
    
    // Site Overview
    siteOverviewBackToSites: "Retour aux sites",
    siteOverviewLastCrawled: "Dernier crawl",
    siteOverviewStartCrawl: "Démarrer un nouveau crawl",
    siteOverviewStartingCrawl: "Démarrage du crawl...",
    siteOverviewRenderJs: "Rendre JavaScript (plus lent, mais meilleur pour les SPA)",
    siteOverviewCriticalIssues: "Problèmes critiques",
    siteOverviewHighPriority: "Haute priorité",
    siteOverviewMediumPriority: "Priorité moyenne",
    siteOverviewCrawlHistory: "Historique des crawls",
    siteOverviewCrawls: "crawls",
    siteOverviewAllIssues: "Tous les problèmes",
    siteOverviewOpenIssues: "problèmes ouverts",
    siteOverviewPages: "Pages",
    siteOverviewPagesCrawled: "pages crawlées",
    siteOverviewHealthReport: "Rapport de santé",
    siteOverviewViewTrends: "Voir les tendances de performance",
    siteOverviewCompetitors: "Concurrents",
    siteOverviewBenchmark: "Benchmark contre les concurrents",
    siteOverviewCriticalAttention: "Problèmes critiques nécessitant une attention",
    siteOverviewView: "Voir",
    
    // Issues Page
    issuesTitle: "Problèmes",
    issuesFound: "problèmes trouvés",
    issuesFilters: "Filtres",
    issuesAllSeverity: "Toutes les sévérités",
    issuesCritical: "Critique",
    issuesHigh: "Élevé",
    issuesMedium: "Moyen",
    issuesAllStatus: "Tous les statuts",
    issuesOpen: "Ouvert",
    issuesIgnored: "Ignoré",
    issuesFixed: "Corrigé",
    issuesAllTypes: "Tous les types",
    issuesClearFilters: "Effacer les filtres",
    issuesSeverity: "Sévérité",
    issuesType: "Type",
    issuesUrl: "URL",
    issuesMessage: "Message",
    issuesStatus: "Statut",
    issuesNoIssues: "Aucun problème trouvé",
    issuesNoIssuesDesc: "Essayez d'ajuster vos filtres",
    issuesMarkFixed: "Marquer comme corrigé",
    issuesMarkIgnored: "Marquer comme ignoré",
    issuesReopen: "Rouvrir le problème",
    issuesViewOnly: "Vue uniquement",
    
    // Reports Page
    reportsTitle: "Rapports",
    reportsGenerate: "Générer un rapport",
    reportsGenerating: "Génération...",
    reportsSelectSite: "Sélectionner un site",
    reportsAllSites: "Tous les sites",
    reportsDateRange: "Plage de dates",
    reportsFrom: "Du",
    reportsTo: "Au",
    reportsIncludeComparison: "Inclure la comparaison avec la période précédente",
    reportsNoReports: "Aucun rapport pour le moment",
    reportsNoReportsDesc: "Générez votre premier rapport pour commencer",
    reportsSite: "Site",
    reportsType: "Type",
    reportsPeriod: "Période",
    reportsCreated: "Créé",
    reportsSummary: "Résumé",
    reportsManual: "Manuel",
    reportsScheduled: "Planifié",
    reportsPages: "pages",
    reportsTotalIssues: "problèmes totaux",
    reportsDownload: "Télécharger",
    
    // Analytics Page
    analyticsTitle: "Analytique",
    analyticsSubtitle: "Suivez les performances SEO et les tendances sur vos sites",
    analyticsSelectSite: "Sélectionner un site",
    analyticsDateRange: "Plage de dates",
    analyticsLast30Days: "30 derniers jours",
    analyticsLast90Days: "90 derniers jours",
    analyticsLast6Months: "6 derniers mois",
    analyticsLast12Months: "12 derniers mois",
    analyticsDomainRating: "Domain Rating",
    analyticsBacklinks: "Backlinks",
    analyticsOrganicTraffic: "Trafic organique",
    analyticsClicks: "Clics",
    analyticsImpressions: "Impressions",
    
    // Billing Page
    billingTitle: "Facturation & Abonnement",
    billingCurrentPlan: "Plan actuel",
    billingManageBilling: "Gérer la facturation",
    billingUpgrade: "Mettre à niveau le plan",
    billingDowngrade: "Rétrograder",
    billingAvailablePlans: "Plans disponibles",
    billingMonthly: "Mensuel",
    billingPerMonth: "par mois",
    billingSelectPlan: "Sélectionner le plan",
    
    // Settings Page
    settingsTitle: "Paramètres",
    settingsAhrefsTitle: "Intégration Ahrefs",
    settingsAhrefsApiKey: "Clé API Ahrefs",
    settingsAhrefsPlaceholder: "Entrez votre clé API Ahrefs",
    settingsSave: "Enregistrer les modifications",
    settingsSaving: "Enregistrement...",
    settingsWhyAhrefs: "Pourquoi connecter Ahrefs?",
    settingsAccessDenied: "Accès refusé",
    settingsNoPermission: "Vous n'avez pas la permission d'accéder aux paramètres.",
    
    // Common
    commonLoading: "Chargement...",
    commonError: "Erreur",
    commonSuccess: "Succès",
    commonDelete: "Supprimer",
    commonEdit: "Modifier",
    commonSave: "Enregistrer",
    commonCancel: "Annuler",
    commonBack: "Retour",
    commonNext: "Suivant",
    commonPrevious: "Précédent",
    commonSearch: "Rechercher",
    commonFilter: "Filtrer",
    commonExport: "Exporter",
    commonImport: "Importer",
    commonSettings: "Paramètres",
  },
  es: {
    // Navigation
    sites: "Sitios",
    analytics: "Analítica",
    reports: "Informes",
    templates: "Plantillas",
    users: "Usuarios",
    billing: "Facturación",
    settings: "Configuración",
    login: "Iniciar sesión",
    
    // Landing - Hero
    heroPreline: "Análisis SEO impulsado por IA para sitios web modernos",
    heroTitle1: "Mantén tu sitio web",
    heroTitle2: "optimizado para SEO",
    heroSubtitle: "Escaneo automático, priorización por IA e informes completos. Todo lo que necesitas para mantener y mejorar la salud SEO de tu sitio web.",
    heroCtaPrimary: "Iniciar Prueba Gratuita",
    heroCtaSecondary: "Ver Demo",
    
    // Landing - Features
    featuresTitle: "Todo lo que necesitas para la monitorización SEO",
    featuresSubtitle: "Desde escaneo automático hasta informes detallados - tenemos todas las herramientas que necesitas",
    
    feature1Title: "Rastreo Automático del Sitio",
    feature1Desc: "Rastrea todas las páginas de tu sitio web e identifica automáticamente problemas SEO",
    
    feature2Title: "Problemas Priorizados",
    feature2Desc: "Análisis impulsado por IA que clasifica los problemas por importancia e impacto",
    
    feature3Title: "Métricas de Rendimiento",
    feature3Desc: "Monitorea Core Web Vitals, tiempo de carga y otras métricas de rendimiento importantes",
    
    feature4Title: "Informes Automatizados",
    feature4Desc: "Programa informes PDF semanales o mensuales para clientes",
    
    feature5Title: "Rastreos Programados",
    feature5Desc: "Monitorización automática de cambios en el sitio web y nuevos problemas",
    
    feature6Title: "Gestión de Equipo",
    feature6Desc: "Gestiona el acceso de tu equipo con roles y permisos",
    
    // Landing - Use Cases
    useCasesTitle: "Perfecto para todos los que trabajan con SEO",
    useCasesSubtitle: "Ya sea que gestiones tu propio sitio web o prestes servicios a clientes",
    
    useCase1Title: "Para Empresas",
    useCase1Desc: "Perfecto para empresas que quieren control total sobre su salud SEO",
    useCase1Benefit1: "Identifica y corrige problemas SEO antes de que afecten las clasificaciones",
    useCase1Benefit2: "Monitorea métricas competitivas como backlinks y domain rating",
    useCase1Benefit3: "Obtén recomendaciones impulsadas por IA para mejoras",
    useCase1Benefit4: "Exporta datos para análisis más profundos",
    useCase1Cta: "Iniciar Prueba Gratuita",
    
    useCase2Title: "Para Agencias y Consultores",
    useCase2Desc: "Perfecto para quienes prestan servicios SEO a múltiples clientes",
    useCase2Benefit1: "Informes de marca blanca con tu propia identidad",
    useCase2Benefit2: "Gestiona múltiples sitios web de clientes desde una cuenta",
    useCase2Benefit3: "Automatiza tareas SEO repetitivas",
    useCase2Benefit4: "Muestra el valor de tus servicios con informes detallados",
    useCase2Cta: "Explorar Enterprise",
    
    // Landing - Pricing
    pricingTitle: "Elige el plan que se ajuste a ti",
    pricingSubtitle: "Todos los planes incluyen 14 días de prueba gratuita. No se requiere tarjeta de crédito.",
    pricingPopular: "Popular",
    pricingPerMonth: "/mes",
    pricingSites: "sitios web",
    pricingCrawls: "rastreos/mes",
    pricingUnlimited: "Ilimitado",
    pricingCtaFree: "Comenzar",
    pricingCtaPaid: "Elegir plan",
    
    // Landing - Final CTA
    ctaTitle: "¿Listo para optimizar tu sitio web?",
    ctaSubtitle: "Únete a miles de empresas y agencias que usan Fixlist para mantener sus sitios web optimizados para SEO.",
    ctaButton: "Iniciar Prueba Gratuita Hoy",
    ctaNotice: "No se requiere tarjeta de crédito • 14 días de prueba gratuita • Cancela en cualquier momento",
    
    // Landing - Footer
    footerCopyright: "Todos los derechos reservados.",
    
    // Sites Page
    sitesTitle: "Sitios",
    sitesAddSite: "Agregar sitio",
    sitesNoSites: "Aún no hay sitios",
    sitesNoSitesDesc: "Agregue su primer sitio web para comenzar a monitorear",
    sitesDomain: "Dominio",
    sitesSchedule: "Programación",
    sitesLastCrawl: "Último rastreo",
    sitesIssues: "Problemas",
    sitesActions: "Acciones",
    sitesScheduleDaily: "Diario",
    sitesScheduleWeekly: "Semanal",
    sitesScheduleMonthly: "Mensual",
    sitesScheduleDisabled: "Desactivado",
    sitesStartCrawl: "Iniciar rastreo",
    sitesManageSchedule: "Gestionar programación",
    sitesViewDetails: "Ver detalles",
    sitesDeleteSite: "Eliminar sitio",
    sitesAddSiteDialogTitle: "Agregar nuevo sitio",
    sitesAddSiteDialogDesc: "Ingrese el dominio del sitio web que desea monitorear",
    sitesDomainPlaceholder: "ejemplo.es",
    sitesCancel: "Cancelar",
    sitesAdd: "Agregar",
    
    // Site Overview
    siteOverviewBackToSites: "Volver a sitios",
    siteOverviewLastCrawled: "Último rastreo",
    siteOverviewStartCrawl: "Iniciar nuevo rastreo",
    siteOverviewStartingCrawl: "Iniciando rastreo...",
    siteOverviewRenderJs: "Renderizar JavaScript (más lento, pero mejor para SPAs)",
    siteOverviewCriticalIssues: "Problemas críticos",
    siteOverviewHighPriority: "Alta prioridad",
    siteOverviewMediumPriority: "Prioridad media",
    siteOverviewCrawlHistory: "Historial de rastreos",
    siteOverviewCrawls: "rastreos",
    siteOverviewAllIssues: "Todos los problemas",
    siteOverviewOpenIssues: "problemas abiertos",
    siteOverviewPages: "Páginas",
    siteOverviewPagesCrawled: "páginas rastreadas",
    siteOverviewHealthReport: "Informe de salud",
    siteOverviewViewTrends: "Ver tendencias de rendimiento",
    siteOverviewCompetitors: "Competidores",
    siteOverviewBenchmark: "Benchmark contra competidores",
    siteOverviewCriticalAttention: "Problemas críticos que requieren atención",
    siteOverviewView: "Ver",
    
    // Issues Page
    issuesTitle: "Problemas",
    issuesFound: "problemas encontrados",
    issuesFilters: "Filtros",
    issuesAllSeverity: "Todas las severidades",
    issuesCritical: "Crítico",
    issuesHigh: "Alto",
    issuesMedium: "Medio",
    issuesAllStatus: "Todos los estados",
    issuesOpen: "Abierto",
    issuesIgnored: "Ignorado",
    issuesFixed: "Corregido",
    issuesAllTypes: "Todos los tipos",
    issuesClearFilters: "Limpiar filtros",
    issuesSeverity: "Severidad",
    issuesType: "Tipo",
    issuesUrl: "URL",
    issuesMessage: "Mensaje",
    issuesStatus: "Estado",
    issuesNoIssues: "No se encontraron problemas",
    issuesNoIssuesDesc: "Intente ajustar sus filtros",
    issuesMarkFixed: "Marcar como corregido",
    issuesMarkIgnored: "Marcar como ignorado",
    issuesReopen: "Reabrir problema",
    issuesViewOnly: "Solo ver",
    
    // Reports Page
    reportsTitle: "Informes",
    reportsGenerate: "Generar informe",
    reportsGenerating: "Generando...",
    reportsSelectSite: "Seleccionar un sitio",
    reportsAllSites: "Todos los sitios",
    reportsDateRange: "Rango de fechas",
    reportsFrom: "Desde",
    reportsTo: "Hasta",
    reportsIncludeComparison: "Incluir comparación con período anterior",
    reportsNoReports: "Aún no hay informes",
    reportsNoReportsDesc: "Genere su primer informe para comenzar",
    reportsSite: "Sitio",
    reportsType: "Tipo",
    reportsPeriod: "Período",
    reportsCreated: "Creado",
    reportsSummary: "Resumen",
    reportsManual: "Manual",
    reportsScheduled: "Programado",
    reportsPages: "páginas",
    reportsTotalIssues: "problemas totales",
    reportsDownload: "Descargar",
    
    // Analytics Page
    analyticsTitle: "Analítica",
    analyticsSubtitle: "Rastree el rendimiento SEO y las tendencias en sus sitios",
    analyticsSelectSite: "Seleccionar un sitio",
    analyticsDateRange: "Rango de fechas",
    analyticsLast30Days: "Últimos 30 días",
    analyticsLast90Days: "Últimos 90 días",
    analyticsLast6Months: "Últimos 6 meses",
    analyticsLast12Months: "Últimos 12 meses",
    analyticsDomainRating: "Domain Rating",
    analyticsBacklinks: "Backlinks",
    analyticsOrganicTraffic: "Tráfico orgánico",
    analyticsClicks: "Clics",
    analyticsImpressions: "Impresiones",
    
    // Billing Page
    billingTitle: "Facturación y Suscripción",
    billingCurrentPlan: "Plan actual",
    billingManageBilling: "Gestionar facturación",
    billingUpgrade: "Actualizar plan",
    billingDowngrade: "Bajar de categoría",
    billingAvailablePlans: "Planes disponibles",
    billingMonthly: "Mensual",
    billingPerMonth: "por mes",
    billingSelectPlan: "Seleccionar plan",
    
    // Settings Page
    settingsTitle: "Configuración",
    settingsAhrefsTitle: "Integración Ahrefs",
    settingsAhrefsApiKey: "Clave API Ahrefs",
    settingsAhrefsPlaceholder: "Ingrese su clave API de Ahrefs",
    settingsSave: "Guardar cambios",
    settingsSaving: "Guardando...",
    settingsWhyAhrefs: "¿Por qué conectar Ahrefs?",
    settingsAccessDenied: "Acceso denegado",
    settingsNoPermission: "No tiene permiso para acceder a la configuración.",
    
    // Common
    commonLoading: "Cargando...",
    commonError: "Error",
    commonSuccess: "Éxito",
    commonDelete: "Eliminar",
    commonEdit: "Editar",
    commonSave: "Guardar",
    commonCancel: "Cancelar",
    commonBack: "Atrás",
    commonNext: "Siguiente",
    commonPrevious: "Anterior",
    commonSearch: "Buscar",
    commonFilter: "Filtrar",
    commonExport: "Exportar",
    commonImport: "Importar",
    commonSettings: "Configuración",
  },
};

async function detectLanguageFromIP() {
  try {
    const response = await fetch('https://ipapi.co/json/');
    const data = await response.json();
    const countryCode = data.country_code;
    
    // Map country codes to languages
    const countryLanguageMap = {
      'NO': 'no', 'SJ': 'no',
      'SE': 'sv',
      'DK': 'da',
      'DE': 'de', 'AT': 'de', 'CH': 'de',
      'FR': 'fr', 'BE': 'fr', 'LU': 'fr',
      'ES': 'es', 'MX': 'es', 'AR': 'es', 'CO': 'es', 'CL': 'es', 'PE': 'es',
    };
    
    return countryLanguageMap[countryCode] || 'en';
  } catch (error) {
    console.error('Failed to detect language:', error);
    return 'en';
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const savedLang = localStorage.getItem('language');
    if (savedLang) {
      setLanguage(savedLang);
      setLoading(false);
    } else {
      detectLanguageFromIP().then(detectedLang => {
        setLanguage(detectedLang);
        localStorage.setItem('language', detectedLang);
        setLoading(false);
      });
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, loading }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}